//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Pipeline.rc
//
#define IDOK4                           2
#define IDC_TAPEUTILS_OPS               3
#define IDC_TAPEUTILS_OPTS              3
#define ID_RENDER_START                 3
#define IDOK2                           3
#define ID_RENDQUEUE_LOAD               4
#define IDOK3                           4
#define ID_RENDQUEUE_NEW                5
#define ID_BATCHCLIP_LOAD               6
#define ID_BATCHCLIP_NEW                7
#define IDD_BATCHCLIP                   8
#define ID_BATCHCLIP_SAVE               9
#define IDC_BATCHCLIP_LIST              10
#define IDC_BATCHCLIP_ENTRY_STARTLABEL  11
#define IDC_BATCHCLIP_ENTRY_SRCLENGTHLABEL 12
#define IDC_BATCHCLIP_ENTRY_LOOPSLABEL  13
#define IDC_BATCHCLIP_ENTRY_LENGTHLABEL 14
#define IDC_BATCHCLIP_ENTRY_ENDLABEL    15
#define IDC_BATCHCLIP_ENTRY_DSTARTLABEL 16
#define IDC_BATCHCLIP_ENTRY_DENDLABEL   17
#define IDC_BATCHCLIP_ENTRY_SRCLABEL    20
#define IDC_BATCHCLIP_ENTRY_DSTLABEL    21
#define IDC_BATCHCLIP_ENTRY_DEST        22
#define IDC_BATCHCLIP_ENTRY_SRCLENGTH   23
#define IDC_BATCHCLIP_ENTRY_SOURCE      24
#define IDC_BATCHCLIP_SRCDEVLABEL       25
#define IDC_BATCHCLIP_DESTDEVLABEL      26
#define IDC_BATCHCLIP_STARTEDIT         30
#define IDC_BATCHCLIP_STARTSPIN         31
#define IDC_BATCHCLIP_ENDEDIT           32
#define IDC_BATCHCLIP_ENDSPIN           33
#define IDC_BATCHCLIP_LENGTHEDIT        34
#define IDC_BATCHCLIP_LENGTHSPIN        35
#define IDC_BATCHCLIP_LOOPSEDIT         36
#define IDC_BATCHCLIP_LOOPSSPIN         37
#define IDC_BATCHCLIP_DSTARTEDIT        38
#define IDC_BATCHCLIP_DSTARTSPIN        39
#define IDC_BATCHCLIP_DENDEDIT          40
#define IDC_BATCHCLIP_DENDSPIN          41
#define IDC_BATCHCLIP_ENTRY_FRAME       42
#define IDC_BATCHCLIP_REELNAME_REEL     43
#define IDC_BATCHCLIP_REELNAME_CLIP     44
#define IDC_BATCHCLIP_REELNAME_REELLABEL 45
#define IDC_BATCHCLIP_REELNAME_CLIPLABEL 46
#define ID_BATCHCLIP_ADD                50
#define ID_BATCHCLIP_DEL                51
#define ID_BATCHCLIP_SHOWBTN            52
#define ID_BATCHCLIP_DEST               53
#define ID_BATCHCLIP_SOURCE             54
#define ID_BATCHCLIP_STARTBUTTON        55
#define ID_BCCRASHREC                   56
#define ID_BATCHCLIP_SWAP               57
#define ID_BATCHCLIP_IMPORTEDL          58
#define IC_BATCHCLIP_SETSRCIN           60
#define IC_BATCHCLIP_SETSRCOUT          61
#define IC_BATCHCLIP_SETDESTIN          62
#define IC_BATCHCLIP_SETDESTOUT         63
#define ID_BATCHCLIP_OFFSET             64
#define IDD_ABOUTBOX                    100
#define IDD_TAPEUTILS                   103
#define IDC_POINTER_DRAG                104
#define IDC_POINTER_DRAGSCROLL          105
#define IDD_PREF_GENERAL                106
#define IDD_PREF_VIEW                   107
#define IDR_MAINFRAME                   128
#define IDR_FLOWTYPE                    129
#define IDR_VIEWBAR                     129
#define IDS_MSG_NOHASP                  130
#define IDS_MSG_WRONGHASP               131
#define IDS_MSG_WRONGKEYTYPE            132
#define IDS_MSG_ILLEGAL                 133
#define IDR_MAINFRAMEHOT                134
#define IDR_VIEWBARHOT                  135
#define IDR_DFCGTYPE                    136
#define IDD_PREF_DEBUG                  168
#define IDD_PREF_VIDMODE                171
#define IDD_PREF_DEFAULTS               172
#define IDD_PREF_TIMELINE               173
#define IDB_EYEON_LOGO                  219
#define ID_OPERATORBAR                  220
#define IDB_COMPRESS_TEST               221
#define IDB_BROWSE                      222
#define IDB_ZOOMIN                      223
#define IDB_ZOOMOUT                     224
#define IDB_NORMALBUTTON                225
#define IDB_SELECTEDBUTTON              226
#define IDB_DISABLEDBUTTON              227
#define IDB_RENDERSTARTBUTTON           228
#define IDB_RENDERSTOPBUTTON            229
#define IDB_LABELARROWUP                230
#define IDB_LABELARROWDOWN              231
#define IDB_PRESSEDBUTTON               232
#define IDB_DISABLEDPRESSEDBUTTON       233
#define IDB_CHECKMARK                   234
#define IDB_CHECKNORMAL                 235
#define IDB_CHECKDISABLED               236
#define IDB_CHECKSELECTED               237
#define IDB_CHECKSELECTEDDISABLED       238
#define IDD_PREF_PREVIEW                239
#define IDD_PREF_SAVER                  240
#define IDB_RADIOCHECKMARK              241
#define IDB_BACKGROUND                  242
#define IDB_SLIDER_CHANNEL              243
#define IDB_SLIDER_KNOB                 244
#define IDB_BUTTONHOVER                 245
#define IDB_CHECKHOVER                  246
#define IDB_SIZER                       247
#define IDB_ICONARROWUP                 248
#define IDB_ICONARROWDOWN               249
#define IDB_ICONARROWRIGHT              250
#define IDB_ICONARROWLEFT               251
#define IDB_WALRUS                      252
#define IDB_WALRUS_LEFT                 253
#define IDB_WALRUS_RIGHT                254
#define THIS_SEEMS_TO_BE_A_SPECIAL_ID   256
#define IDD_CUSTOM_SCALE                258
#define IDB_UPARROW_UP                  259
#define IDB_UPARROW_DOWN                260
#define IDB_UPARROW_MASK                261
#define IDB_LEFTARROW_UP                262
#define IDB_LEFTARROW_DOWN              263
#define IDB_LEFTARROW_MASK              264
#define IDB_DOWNARROW_UP                265
#define IDB_DOWNARROW_DOWN              266
#define IDB_DOWNARROW_MASK              267
#define IDB_RIGHTARROW_UP               268
#define IDB_RIGHTARROW_DOWN             269
#define IDB_RIGHTARROW_MASK             270
#define IDB_SCROLLKNOB_HORIZ            271
#define IDB_SCROLLKNOB_VERT             272
#define IDC_RangeDrag                   275
#define IDC_RangeExtendLeft             276
#define IDC_RangeExtendRight            277
#define IDD_CUSTOMISE_TOOLBARS          302
#define IDC_POINTER_COPY                315
#define IDC_RangeExtendLeft1            317
#define IDC_POINTER_NONE                329
#define IDD_GET_STRING                  329
#define IDD_PREF_BINS                   330
#define IDB_TILE_COLORCURVES            331
#define IDC_POINTER_ON_POINT            332
#define IDB_TILE_DEFOCUS                333
#define IDB_TILE_GROUP                  334
#define IDC_COLPICK                     335
#define IDB_FLOW_ICON                   336
#define IDD_FREEHANDCTRL                337
#define IDD_PREF_MEMORY                 338
#define IDB_TILE_UNKNOWN                339
#define IDB_TILE_BACKGROUND             340
#define IDB_TILE_BLUR                   341
#define IDB_TILE_BOOLEAN                342
#define IDB_TILE_BRIGHTNESS             343
#define IDB_TILE_CHROMAKEYER            344
#define IDB_TILE_COLORCORRECTOR         345
#define IDB_TILE_COLORGAIN              346
#define IDB_TILE_COLORSPACE             347
#define IDB_TILE_COORDSPACE             348
#define IDB_TILE_CORNERPOSITIONER       349
#define IDB_TILE_CROP                   350
#define IDB_TILE_CUSTOMFILTER           351
#define IDB_TILE_DEFORM                 352
#define IDB_TILE_DENT                   353
#define IDB_TILE_DISSOLVE               354
#define IDB_TILE_DRIP                   355
#define IDB_TILE_DVE                    356
#define IDB_TILE_FILTER                 357
#define IDB_TILE_GLOW                   358
#define IDB_TILE_HIGHLIGHT              359
#define IDB_TILE_LOADER                 360
#define IDB_TILE_LUMAKEYER              361
#define IDB_TILE_MANDELBROT             362
#define IDB_TILE_MATTECONTROL           363
#define IDB_TILE_MERGE                  364
#define IDB_TILE_MOTIONBLUR             365
#define IDB_TILE_PERSPECTIVEPOSITIONER  366
#define IDB_TILE_PLASMA                 367
#define IDB_TILE_RESIZE                 368
#define IDB_TILE_SAVER                  369
#define IDB_TILE_SHADOW                 370
#define IDB_TILE_TIMESTRETCHER          371
#define IDB_TILE_TRANSFORM              372
#define IDB_TILE_TRACKER                373
#define IDB_TILE_ULTRAKEYER             374
#define IDB_TILE_VORTEX                 375
#define IDB_TILE_CHARGEN                376
#define IDD_PREF_LAYOUT                 377
#define IDD_PREF_APPEARANCE             378
#define IDC_POINTER_URL                 379
#define IDC_PENCIL                      381
#define IDD_TAPEUTILS_OPTIONS           381
#define IDC_FLOOD                       382
#define IDB_TILE_CINEONLOG              383
#define IDB_TILE_PAINT                  384
#define IDB_TILE_PERLIN                 385
#define IDB_TILE_RUNCOMMAND             386
#define IDB_TAPEUTILS_DISK2TAPE_IMG     387
#define IDB_TAPEUTILS_TAPE2DISK_IMG     388
#define IDB_TAPEUTILS_SKIPFWD_IMG       389
#define IDB_TILE_ERODEDILATE            390
#define IDB_TAPEUTILS_SKIPBACK_IMG      391
#define IDI_TAPEUTILS_TAPE              392
#define IDI_TAPEUTILS_DISK              393
#define IDD_POSTREG_DIALOG              394
#define IDB_LOCKED                      395
#define IDB_NOUPDATE                    396
#define IDB_TILE_TEXT2000               397
#define IDD_SPLINE_TAPER                398
#define IDB_PT_COLOR                    401
#define IDB_TILE_FIELDS                 402
#define IDB_TILE_TIMESPEED              403
#define IDB_PT_CONTROLS                 404
#define IDB_TILE_TRAILS                 405
#define IDB_PT_ALPHA                    406
#define IDB_TILE_FASTNOISE              407
#define IDB_PT_CIRCLE                   408
#define IDB_PT_TRIANGLE                 409
#define IDB_PT_RECTANGLE                410
#define IDB_PT_POLYLINE                 411
#define IDB_PT_RED                      412
#define IDB_PT_BLUE                     413
#define IDB_PT_GREEN                    414
#define IDB_PT_OVERLAY                  415
#define IDB_TILE_STABILIZE              416
#define IDB_TILE_CORNERTRACKER          417
#define IDB_TILE_HOTSPOT                418
#define IDB_TILE_LETTERBOX              419
#define IDB_TILE_PSEUDOCOLOR            420
#define IDB_TILE_GRAIN                  421
#define IDB_TILE_DISPLACE               422
#define IDB_TILE_AUTOGAIN               423
#define IDD_EDIT_POINT                  424
#define IDD_PREF_BATCH                  425
#define IDD_BATCHCLIP_REELNAME          426
#define IDB_PAINT_AIRBRUSH_COLD         427
#define IDD_BCCRASHREC                  427
#define IDB_PAINT_CLONEBRUSH_COLD       428
#define IDD_PREF_NETWORK                428
#define IDB_PAINT_RECTANGLE_COLD        429
#define IDB_PAINT_CIRCLE_COLD           430
#define IDB_PAINT_SELECT_COLD           431
#define IDB_PAINT_AIRBRUSH_HOT          432
#define IDB_PAINT_CLONEBRUSH_HOT        433
#define IDB_PAINT_RECTANGLE_HOT         434
#define IDB_PAINT_CIRCLE_HOT            435
#define IDB_PAINT_SELECT_HOT            436
#define IDB_PAINT_POLYLINE_COLD         437
#define IDB_PAINT_POLYLINE_HOT          438
#define IDB_TILE_GAMUT                  439
#define IDD_NETWORK                     440
#define IDB_PT_MASK                     441
#define IDB_TILE_DEPTHBLUR              442
#define IDB_TILE_TEXTURE                443
#define IDB_TILE_SHADER                 444
#define IDB_TILE_DIFFERENCEKEYER        445
#define IDB_TILE_FOG                    446
#define IDD_NETWORK_SLAVE               447
#define IDC_CLOSE                       448
#define IDD_TWOFIVE_DIALOG              449
#define IDB_TILE_GRID                   450
#define IDR_ENGINEMAINFRAME             452
#define IDB_PT_DISABLEDMASK             453
#define IDD_STATUS                      454
#define IDB_PT_DISABLEDCIRCLE           454
#define IDI_TASKBAR                     455
#define IDB_PT_DISABLEDPOLY             455
#define IDC_POINTER_ZOOMIN              456
#define IDB_PT_DISABLEDTRIANGLE         456
#define IDC_POINTER_ZOOMOUT             457
#define IDB_PT_DISABLEDRECTANGLE        457
#define IDC_PENCIL1                     458
#define IDC_PENCIL_HIT                  461
#define IDB_TILE_CAMERASHAKE            462
#define IDC_INSERT_HIT                  463
#define IDI_TASKBAR_ACTIVE1             468
#define IDI_TASKBAR_ACTIVE2             469
#define IDD_SPLINE_ADD_REMOVE           471
#define IDB_BOX_BLANK                   472
#define IDB_BOX_UNCHECKED               473
#define IDB_BOX_CHECKED                 474
#define IDB_PT_ONE2ONE                  475
#define IDB_BOX_ACTIVE                  476
#define IDB_BOX_GRAYED                  476
#define IDC_POINTER_DRAGZOOM            478
#define IDD_LICENSE_DIALOG              479
#define IDC_POINTER_ON                  479
#define IDB_TILE_CUSTOM                 480
#define IDC_POINTER_LEFTRIGHT           480
#define IDB_PT_ABUFFER                  481
#define IDC_POINTER_ADD                 481
#define IDB_DRAW_CLICK_HOT              482
#define IDC_POINTER_DELETE              482
#define IDB_DRAW_CLICK_COLD             483
#define IDB_DRAW_INSERTMODIFY_HOT       484
#define IDB_DRAW_INSERTMODIFY_COLD      485
#define IDB_DRAW_FREEHAND_HOT           486
#define IDB_DRAW_FREEHAND_COLD          487
#define IDB_DRAW_DONE_HOT               488
#define IDB_DRAW_DONE_COLD              489
#define IDB_PT_BBUFFER                  490
#define IDB_DRAW_MODIFY_HOT             491
#define IDB_DRAW_MODIFY_COLD            492
#define IDB_CURRENT_TIME_ONLY_COLD      493
#define IDB_CURRENT_TIME_ONLY_HOT       494
#define IDB_PATH_CLOSED_COLD            495
#define IDB_PATH_CLOSED_HOT             496
#define IDB_PATH_SMOOTH_COLD            497
#define IDB_PATH_SMOOTH_HOT             498
#define IDB_PATH_LINEAR_COLD            499
#define IDB_PATH_LINEAR_HOT             500
#define IDB_POINTS_SELECT_ALL_COLD      501
#define IDB_POINTS_SELECT_ALL_HOT       502
#define IDB_SHOW_KEYS_COLD              503
#define IDB_SHOW_KEYS_HOT               504
#define IDB_SHOW_HANDLES_COLD           505
#define IDB_SHOW_HANDLES_HOT            506
#define IDB_POINT_LOCK_COLD             507
#define IDB_POINT_LOCK_HOT              508
#define IDB_PATH_SHAPE_COLD             509
#define IDB_PATH_SHAPE_HOT              510
#define IDB_POINT_REDUCE_COLD           511
#define IDB_POINT_REDUCE_HOT            512
#define IDB_RENDER_STOP_COLD            513
#define IDB_RENDER_STOP_HOT             514
#define IDB_DELETE_COLD                 515
#define IDB_DELETE_HOT                  516
#define IDB_CUT_COLD                    517
#define IDB_CUT_HOT                     518
#define IDD_FREEHANDLUTCTRL             519
#define IDB_PT_PAINT                    520
#define IDB_PT_DISABLEDPAINT            521
#define IDD_PREF_FLOW                   522
#define IDD_PREF_TWEAKS                 523
#define IDD_FLOATING_LISTBOX            526
#define IDD_RENDER_SETTINGS             527
#define IDC_PREF_FLOW_STAT5             530
#define IDC_PREF_FLOW_STAT6             531
#define IDC_PREF_FLOW_GROUP_OPACITY     532
#define IDB_NGON_SOLID                  533
#define IDB_NGON_SHADED_IN              534
#define IDB_NGON_SHADED_OUT             535
#define IDB_NGON_STAR                   536
#define IDB_NGON_CIRCLE                 537
#define IDB_NGON_CIRCULAR               538
#define IDB_NGON_SOFT_CIRCULAR          539
#define IDB_TILE_LIGHTTRIM              540
#define IDD_DO_CACHETODISK              541
#define IDD_PREF_SCRIPT                 542
#define IDB_TILE_POLYLINE               543
#define IDB_TILE_RANKFILTER             544
#define IDB_TILE_RECTANGLE              545
#define IDB_TILE_SCALE                  546
#define IDB_TILE_SOFTGLOW               547
#define IDB_BACKGROUND_VERTICAL_H       548
#define IDB_BACKGROUND_HORIZONTAL_H     549
#define IDB_BACKGROUND_SOLID_H          550
#define IDB_BACKGROUND_FOURCORNER_H     551
#define IDB_GRADIENTARROWNORMAL         552
#define IDB_GRADIENTARROWSELECTED       553
#define IDB_GRADIENTGRADIENT            554
#define IDB_GRADIENTBACKDROP            555
#define IDB_TILE_TRIANGLE               556
#define IDB_TILE_UNSHARPMASK            557
#define IDB_TILE_WAND                   558
#define IDB_TILE_WHITEBALANCE           559
#define IDB_TILE_ELLIPSE                560
#define IDB_TILE_3D_BACKGROUND          561
#define IDB_TILE_3D_CUBE                562
#define IDB_TILE_3D_EPS_LOADER          563
#define IDB_TILE_3D_IMAGE               564
#define IDB_TILE_3D_MERGE               566
#define IDB_TILE_3D_TRANSFORM           567
#define IDB_GRADIENTBUTTONPREVIOUS      568
#define IDB_GRADIENTBUTTONNEXT          569
#define IDB_GRADIENTBUTTONDELETE        570
#define IDB_BACKGROUND_GRADIENT_H       571
#define IDB_TILE_PAVOID                 572
#define IDB_TILE_PBOUNCE                573
#define IDB_TILE_PCHANGESTYLE           574
#define IDB_TILE_PCUSTOM                575
#define IDB_TILE_PDIRECTIONALFORCE      576
#define IDB_TILE_PEMITTER               577
#define IDB_TILE_PFLOCK                 578
#define IDB_TILE_PFRICTION              579
#define IDB_TILE_PGRADIENTFORCE         580
#define IDB_TILE_PKILL                  581
#define IDB_TILE_PMERGE                 582
#define IDB_TILE_PPOINTFORCE            583
#define IDB_TILE_PRENDER                584
#define IDB_TILE_PSPAWN                 585
#define IDB_TILE_PTANGENTFORCE          586
#define IDB_TILE_PTURBULENCE            587
#define IDB_TILE_PVORTEX                588
#define IDB_GENERIC_ROTATION_XYZ_H      589
#define IDB_GENERIC_ROTATION_XZY_H      590
#define IDB_GENERIC_ROTATION_YXZ_H      591
#define IDB_GENERIC_ROTATION_YZX_H      592
#define IDB_GENERIC_ROTATION_ZXY_H      593
#define IDB_GENERIC_ROTATION_ZYX_H      594
#define IDB_PT_BITMAP                   595
#define IDB_PT_DISABLEDBITMAP           596
#define IDB_PT_DEPTH                    597
#define IDB_PT_DISABLEDDEPTH            598
#define IDB_PT_NORMALISE                599
#define IDB_PAINT_COPY_POLYLINE_COLD    600
#define IDB_PAINT_COPY_POLYLINE_HOT     601
#define IDB_PAINT_GROUP_COLD            602
#define IDB_PAINT_GROUP_HOT             603
#define IDB_TRACK_REVERSE_C             604
#define IDB_TRACK_REVERSE_H             605
#define IDB_TRACK_REVERSETIME_C         606
#define IDB_TRACK_REVERSETIME_H         607
#define IDB_TRACK_STOP_C                608
#define IDB_TRACK_STOP_H                609
#define IDB_TRACK_FORWARDTIME_C         610
#define IDB_TRACK_FORWARDTIME_H         611
#define IDB_TRACK_FORWARD_C             612
#define IDB_TRACK_FORWARD_H             613
#define IDB_CHECKLIST_ADD_H             614
#define IDB_CHECKLIST_DELETE_H          615
#define IDB_MC_MAGNET_ACTIVE_COLD       616
#define IDB_MC_MAGNET_ACTIVE_HOT        617
#define IDB_MC_SHOW_SUBDIVISION_COLD    618
#define IDB_MC_SHOW_SUBDIVISION_HOT     619
#define IDB_MC_SHOW_GRID_COLD           620
#define IDB_MC_SHOW_GRID_HOT            621
#define IDD_BETTERRENDERQUEUE           622
#define IDB_SLAVEICONS                  623
#define IDB_PUBLISH_POINTS_COLD         624
#define IDB_PUBLISH_POINTS_HOT          625
#define IDB_PUBLISH_TO_PATH_COLD        626
#define IDB_PUBLISH_TO_PATH_HOT         627
#define IDB_FOLLOW_PUBLISHED_COLD       628
#define IDB_FOLLOW_PUBLISHED_HOT        629
#define IDI_TASKBAR_INACTIVE            630
#define IDB_MC_AUTO_SMOOTH_COLD         632
#define IDB_MC_AUTO_SMOOTH_HOT          633
#define IDB_MC_ZUNDER_COLD              634
#define IDB_MC_ZUNDER_HOT               635
#define IDB_MC_ZSAME_COLD               636
#define IDB_MC_ZSAME_HOT                637
#define IDB_MC_ZOVER_COLD               638
#define IDB_MC_ZOVER_HOT                639
#define IDB_MC_RESET_SELECTED_COLD      640
#define IDB_MC_RESET_SELECTED_HOT       641
#define IDB_MC_RESET_ALL_COLD           642
#define IDB_MC_RESET_ALL_HOT            643
#define IDB_MC_SETUV_COLD               644
#define IDB_MC_SETUV_HOT                645
#define IDB_PT_WAND                     646
#define IDB_PT_DISABLEDWAND             647
#define IDB_PAINT_FILL_HOT              648
#define IDB_PAINT_FILL_COLD             649
#define IDB_PAINT_COPY_CIRCLE_COLD      650
#define IDB_PAINT_COPY_CIRCLE_HOT       651
#define IDB_PAINT_COPY_RECTANGLE_COLD   652
#define IDB_PAINT_COPY_RECTANGLE_HOT    653
#define IDB_LIBRARY_ADD_H               654
#define IDB_LIBRARY_RETRIEVE_H          655
#define IDB_LIBRARY_DELETE_H            656
#define IDB_PAINT_AUTOROTO_COLD         657
#define IDB_PAINT_AUTOROTO_HOT          658
#define IDD_REPORT_BUG                  659
#define IDD_PREF_CLUSTER                660
#define IDB_SPL_STEP_IN                 661
#define IDB_SPL_STEP_OUT                662
#define IDB_TIME_STRETCHING             663
#define IDB_POINTS_REVERSE              664
#define IDB_SET_LOOP                    665
#define IDB_SET_PINGPONG                666
#define IDB_SET_RELATIVE                667
#define IDB_SHOW_KEYMARKERS             668
#define IDB_SHOW_ALLSPLINES             669
#define IDB_ZOOM_TO_RECTANGLE           670
#define IDB_HIDE_ALLSPLINES             671
#define IDB_SHOW_SPREADSHEET            672
#define IDB_SPLINE_CHECKLISTBOX         673
#define IDD_PREF_PATHMAP                674
#define IDD_PREF_SOFTDPS                675
#define IDD_FINDTOOLS                   676
#define IDD_POINT_WEIGHT                677
#define IDD_EDIT_SPIRAL                 678
#define IDD_EDIT_RECTANGLE              679
#define IDB_TILE_3D_LIGHTAMBIENT        680
#define IDD_PREF_PATHMAP1               680
#define IDD_PREF_BINSERVERS             680
#define IDB_TILE_3D_LIGHTDIRECTIONAL    681
#define IDD_PREF_BINSECURITY            681
#define IDB_TILE_3D_LIGHTPOINT          682
#define IDB_TILE_3D_LIGHTSPOT           683
#define IDB_TILE_3D_SHAPE               684
#define IDB_TILE_3D_CAMERA              685
#define IDB_TILE_3D_DUPLICATE           686
#define IDB_TILE_3D_RENDERER            687
#define IDB_TILE_BSPLINE                688
#define IDB_TILE_BITMAP                 689
#define IDB_TILE_REMOVENOISE            690
#define IDB_TILE_SHARPEN                691
#define IDB_FOLDER_ICON                 692
#define IDB_TILE_MASKPAINT              693
#define IDB_TILE_SINGLETRACKER          694
#define IDB_TILE_3D_LOCATOR             695
#define IDB_TILE_3D_POINTCLOUD          696
#define IDB_TILE_PIMAGEEMITTER          697
#define IDB_TILE_CHANGEDEPTH            698
#define IDB_TILE_TV                     699
#define IDD_PREF_SPLINES                700
#define IDB_SETTINGS_ICON               701
#define IDB_TILE_3D_FBXMESH             702
#define IDD_EXPORT_POLYGON              702
#define IDD_EMPTY_DIALOG                703
#define IDC_FREQ_NEWDIR                 704
#define IDC_FREQ_UPDIR                  705
#define IDC_FREQ_PREVDIR                706
#define IDC_FREQ_DELETE                 707
#define IDC_FREQ_DETAILS                708
#define IDC_FREQ_THUMBS                 709
#define IDC_WAIT_SHAPE                  710
#define IDC_WAIT_GRADIENT               711
#define IDD_EXPORT_ALUT                 712
#define IDD_SLIDER_EXPRESSION           713
#define IDB_TILE_3D_TEXT                714
#define IDB_TILE_3D_BENDER              715
#define IDB_TILE_3D_PROJECTOR           716
#define IDB_TILE_VECTORDISTORT          717
#define IDB_TILE_SMEEHEE                718
#define IDB_TILE_3D_REPLACEMATERIAL     719
#define IDB_TILE_3D_DISPLACE            720
#define IDB_TILE_FILELUT                721
#define IDC_FREQ_FAVOURITES             722
#define IDC_FREQ_HISTORY                723
#define IDC_FREQ_CALENDAR               724
#define IDC_FREQ_ADDFAVOURITE           725
#define IDD_SAWITZKY_GOLAY_FILTER       726
#define IDC_CURSOR1                     728
#define IDC_POINTER_PROGRESS            728
#define IDC_CURSOR2                     729
#define IDC_DRAGRECT                    729
#define IDC_FREQ_PREVIEW                730
#define IDB_TILE_3D_BLINN               731
#define IDD_PREF_SPLINEVIEW             731
#define IDB_TILE_3D_CATCHER             732
#define IDD_EXPORT_3DLUT                732
#define IDB_TILE_3D_CHANNELBOOLEAN      733
#define IDD_PREF_LOADER                 733
#define IDB_TILE_3D_COOKTORRANCE        734
#define IDD_IMPORT_SHAPE                734
#define IDB_TILE_3D_BUMPMAP             735
#define IDB_TILE_3D_TEXTURE2D           736
#define IDB_TILE_3D_CUBEMAP             737
#define IDB_TILE_3D_FALLOFF             738
#define IDB_TILE_3D_FASTNOISE           739
#define IDB_TILE_3D_FOG                 740
#define IDB_TILE_3D_GRADIENT            741
#define IDB_TILE_3D_MTLMERGE            742
#define IDB_TILE_3D_OVERRIDE            743
#define IDB_TILE_3D_PHONG               744
#define IDB_TILE_3D_REFLECT             745
#define IDB_TILE_3D_SOFTCLIP            746
#define IDB_TILE_3D_SPHEREMAP           747
#define IDB_TILE_3D_STEREOMIX           748
#define IDB_TILE_3D_TEXTURETRANSFORM    749
#define IDB_TILE_3D_UVMAP               750
#define IDB_TILE_3D_WARD                751
#define IDB_TILE_ANAGLYPH               752
#define IDB_TILE_COLORMATRIX            753
#define IDB_TILE_CREATEBUMPMAP          754
#define IDB_TILE_STICKYNOTES            755
#define IDB_TILE_UNDERLAY               756
#define IDB_TILE_RANGESMASK             757
#define IDB_TILE_SETBGCOLOR             758
#define IDB_TILE_SETDOMAIN              759
#define IDB_TILE_VARIBLUR               760
#define IDB_TILE_AUTODOMAIN             761
#define IDB_TILE_3D_FBXEXPORT           762
#define IDB_TILE_FILMGRAIN              763
#define IDB_TILE_DAYSKY                 764
#define IDB_TILE_COMBINER               765
#define IDB_TILE_SPLITTER               766
#define IDB_TILE_HUECURVES              767
#define IDD_PREF_OPENCL                 768
#define IDD_SHAPEIMPORTDLG              769
#define IDC_TIME_CURRENT_TIME_LABEL     1000
#define IDC_TIME_SLIDER                 1001
#define IDC_TAPEUTILS_SKIPGROUP         1001
#define IDC_TIME_RENDER_START_LABEL     1002
#define IDC_TAPEUTILS_REWIND            1002
#define IDC_TIME_CURRENT_TIME           1003
#define IDC_TAPEUTILS_EJECT             1003
#define IDC_TIME_CURRENT_TIME_SPIN      1004
#define IDC_TAPEUTILS_RETENSION         1004
#define IDC_TIME_SHOWBTN                1005
#define IDC_TAPEUTILS_GOTOEND           1005
#define IDC_TIME_RENDER_START           1006
#define IDC_TIME_RENDER_START_SPIN      1007
#define IDDC_OFFSET_EDITY               1007
#define IDC_TIME_RENDER_END_LABEL       1008
#define IDC_TAPEUTILS_STATIC1           1008
#define IDC_TIME_RENDER_END             1009
#define IDC_TAPEUTILS_SCSIINFO          1009
#define IDC_TIME_RENDER_END_SPIN        1010
#define IDC_PREF_GENERAL_DEPTHLABEL     1011
#define IDC_PREF_GENERAL_DEPTHCOMBO     1012
#define IDC_PREF_MEMORY_ENGINEOVERRIDE  1013
#define IDC_PREF_PARALLELISM            1016
#define IDC_PREF_PREVIEW_SLID           1017
#define IDC_PREF_GRABDIST_SLID          1018
#define IDC_PREF_NUMREQ_STAT2           1019
#define IDC_PREF_AUTOPROXY_SLID         1019
#define IDC_PREF_NUMREQ_STAT3           1020
#define IDC_PREF_GRP_2                  1021
#define IDC_PREF_NUMREQ_STAT4           1021
#define IDC_PREF_PREVIEW_GRP            1022
#define IDC_PREF_GRP_3                  1022
#define IDC_PREF_PREVIEW_GRP2           1023
#define IDC_PREF_NUMREQ_STAT5           1023
#define IDC_PREF_GRP_1                  1024
#define IDC_PREF_NUMREQ_STAT6           1024
#define IDC_PREF_NUMREQ_STAT7           1025
#define IDC_PREF_TWEAKS_MAXHEARTBEATS   1026
#define IDC_PREF_TWEAKS_READAHEADBUFTXT 1027
#define IDC_PREF_PREVIEW_STAT1          1028
#define IDC_PREF_TWEAKS_SATPROXYLABEL   1028
#define IDC_PREF_PREVIEW_STAT5          1029
#define IDC_PREF_TWEAKS_SATPROXY        1029
#define IDC_PREF_LOADFLOWTIMEOUT_STAT   1030
#define IDCIDC_PREF_LOADFLOWTIMEOUT_STAT2 1031
#define IDC_PREF_SPLINES_CHK            1032
#define IDC_PREF_LASTDROPPEDTIMEOUT_STAT 1032
#define IDCIDC_PREF_LOADFLOWTIMEOUT_STAT3 1033
#define IDDC_OFFSET_EDITX               1034
#define IDC_PREF_PREVIEW_STAT2          1034
#define IDC_PREF_SIMULBRANCH_RENDER     1035
#define IDC_PREF_PREVIEW_STAT6          1035
#define IDC_PREF_PREVIEW_STAT3          1036
#define IDC_PREF_SIMULBRANCH_INTERACTIVE 1036
#define IDC_PREF_PREVIEW_STAT4          1037
#define IDC_PREF_DEBUG_GRP              1039
#define IDC_PREF_POLYLINES_CHK          1040
#define IDC_PREF_LUTS_CHK               1041
#define IDC_PREF_PATHS_CHK              1042
#define IDC_PREF_DEF_SMOOTH_GRP         1043
#define IDC_PREF_BPOLYLINES_CHK         1044
#define IDM_HIGH_QUALITY_CHK            1053
#define IDM_PROXY_CHK                   1054
#define IDC_AUTOPROXY_CHK               1055
#define IDM_USE_NETWORK_CHK             1056
#define IDC_SELECTIVEUPDATE_CHK         1057
#define IDC_PREF_VIDMODE_TXT            1058
#define IDC_PREF_VIDMODE_FPS_EDT        1059
#define IDC_PREF_NETWORK_TXT2           1059
#define IDC_PREF_VIDMODE_FPS_SPIN       1060
#define IDC_PREF_NETWORK_TXT3           1060
#define IDC_PREF_VIDMODE_FPS_TXT        1061
#define IDC_PREF_NETWORK_TXT4           1061
#define IDC_PREF_VIDMODE_CUST_GRP       1062
#define IDC_PREF_NETWORK_TXT5           1062
#define IDC_PREF_VIDMODE_FPS_TXT2       1063
#define IDC_PREF_NETWORK_TXT6           1063
#define IDC_PREF_VIDMODE_WIDTH_EDT      1064
#define IDC_PREF_NETWORK_TXT7           1064
#define IDC_PREF_VIDMODE_FIELDS_CHK     1065
#define IDC_PREF_VIDMODE_WIDTH_TXT      1066
#define IDC_PREF_VIDMODE_WIDTH_TXT1     1067
#define IDC_PREF_VIDMODE_HEIGHT_EDT     1068
#define IDM_MOTION_BLUR_CHK             1069
#define IDC_PREF_VIDMODE_HEIGHT_TXT     1070
#define IDC_PREF_VIDMODE_HEIGHT_TXT1    1071
#define IDC_PREF_VIDMODE_NEWBTN         1072
#define IDC_PREF_VIDMODE_CBOX           1073
#define IDC_PREF_VIDMODE_COPYBTN        1074
#define IDC_TIME_HOURGLASS              1075
#define IDC_LABEL1                      1077
#define IDC_PREF_VIDMODE_DELBTN         1078
#define IDC_DEFNUMBER                   1079
#define IDC_LABEL2                      1080
#define IDC_EYEON_LOGO                  1080
#define IDC_LABEL3                      1081
#define IDC_AW_LOGO                     1081
#define IDC_DEFPOINT                    1082
#define IDC_DEFBACKGROUND               1083
#define IDC_DEFMERGE                    1084
#define IDC_PREF_DEF_SCALE_SMALL        1085
#define IDC_LABEL8                      1086
#define IDC_PREF_DEF_SCALE_LARGE        1087
#define IDC_PREF_VIEW_SCALE_LARGE       1087
#define IDC_PREF_DEFMERGE_CONNECT       1088
#define IDC_PREF_DEF_TIMECODE_GRP       1089
#define IDC_PREF_DEF_TIMECODE_LABEL     1090
#define IDC_PREF_DEF_SHOW_TIMECODE      1091
#define IDC_AUTO_SAVE                   1092
#define IDC_SAVE_RENDER                 1093
#define IDC_SAVE_DELAY                  1094
#define IDC_PREF_DEF_AUTOSAVEGRP        1095
#define IDC_DELAY_LABEL2                1096
#define IDC_DELAY_SPIN                  1097
#define IDC_DELAY_LABEL1                1098
#define IDC_ABOUT_TEXT2                 1098
#define IDC_ABOUT_TEXT3                 1099
#define IDC_PREF_DEF_SCALECUSTOM_SMALL  1099
#define IDC_ABOUT_TEXT4                 1100
#define IDC_PREF_DEF_CUSTOMSPIN_SMALL   1100
#define IDC_ABOUT_TEXT5                 1101
#define IDC_PREF_DEF_SCALECUSTOM_LARGE  1101
#define IDC_PREF_VIEW_SCALECUSTOM_LARGE 1101
#define IDC_ABOUT_TEXT1                 1102
#define IDC_PREF_DEF_CUSTOMSPIN_LARGE   1102
#define IDC_PREF_VIEW_CUSTOMSPIN_LARGE  1102
#define IDC_PREF_PREVIEW_PATH           1103
#define IDC_PREF_PREVIEW_AVI_BUTTON     1104
#define IDC_PREF_PREVIEW_WIDTH          1105
#define IDC_PREF_PREVIEW_HEIGHT         1106
#define IDC_PREF_PREVIEW_QUICK_RENDER   1107
#define IDC_PREF_PREVIEW_SCALE          1108
#define IDC_PREF_PREVIEW_BROWSE         1109
#define IDC_PREF_PREVIEW_SKIPFRAMES     1109
#define IDC_PREF_PREVIEW_KEEP_ASPECT    1110
#define IDC_PREF_PREVIEW_ACTIVELOADERS  1110
#define IDC_ABOUT_TEXT6                 1111
#define IDC_PREF_PREVIEW_ACTIVELOADERS2 1111
#define IDC_PREF_PREVIEW_ACTIVESAVERS   1111
#define IDC_PREF_DEF_TIMECODE_SMPTE     1112
#define IDC_PREF_DEF_TIMECODE_FEET      1113
#define IDC_PREF_PREVIEW_CODEC_ID       1115
#define IDC_PREF_PREVIEW_KEYFRAMES      1116
#define IDC_PREF_PREVIEW_QUALITY        1117
#define IDC_PREF_PREVIEW_FRAMERATE      1118
#define IDC_PREF_PREVIEW_DATARATE       1119
#define IDC_PREF_AVI_CODECCOMBO         1120
#define IDC_PREF_AVI_QUALITY            1121
#define IDC_PREF_AVI_QUALITYSLIDER      1122
#define IDC_PREF_AVI_KEYCHECK           1123
#define IDC_PREF_AVI_KEYEDIT            1124
#define IDC_PREF_AVI_DATACHECK          1125
#define IDC_PREF_AVI_DATAEDIT           1126
#define IDC_PREF_AVI_SIZELABEL          1127
#define IDC_TIME_GLOBAL_START           1128
#define IDC_TIME_GLOBAL_END             1129
#define IDC_TIME_GLOBAL_START_LABEL     1130
#define IDC_TIME_GLOBAL_END_LABEL       1131
#define IDC_PREF_VIDMODE_ASPECT_TXT     1132
#define IDC_PREF_VIDMODE_ASPECTX_EDT    1133
#define IDC_PREF_VIDMODE_ASPECTY_EDT    1134
#define IDC_CUSTOM_SCALE                1134
#define IDC_PREF_DEF_PERCSTATIC         1135
#define IDC_PREF_DEF_PREVSCALE          1136
#define IDC_PREF_DEF_SCALETITLE         1137
#define IDC_PREF_DEF_ANIMSCALECUSTOM_SMALL 1138
#define IDC_PREF_DEF_ANIMCUSTOMSPIN_SMALL 1139
#define IDC_PREF_DEF_ANIMPERCSTATIC     1140
#define IDC_PREF_DEF_ANIMSCALE_SMALL    1141
#define IDC_PREF_DEF_ANIMSCALETITLE     1142
#define IDC_STATIC2                     1143
#define IDC_PREF_DEF_PREVSCALE2         1143
#define IDC_DEPTH_FULL_RENDER           1144
#define IDC_PREF_DEF_PREVSCALE3         1144
#define IDC_PREF_VIDMODE_PROC_GRP       1145
#define IDC_PREF_DEF_PREVSCALE4         1145
#define IDC_VIDMODE_FULL_RENDER         1146
#define IDC_PREF_DEF_SCALETITLE2        1146
#define IDC_PREF_VIEW_SCALETITLE2       1146
#define IDC_PREF_LOADER_CACHE           1146
#define IDC_PREF_LOADER_CACHE_GRP       1146
#define IDC_DEPTH_INTERACTIVE           1147
#define IDC_TOOLBAR_NEW                 1147
#define IDC_PREF_DEF_PERCSTATIC2        1147
#define IDC_PREF_VIEW_PERCSTATIC2       1147
#define IDC_VIDMODE_INTERACTIVE         1148
#define IDC_TOOLBAR_DEL                 1148
#define IDC_PREF_DEF_ANIMSCALE_LARGE    1148
#define IDC_PREF_VIEW_ANIMSCALE_LARGE   1148
#define IDC_DEPTH_PREVIEW_RENDER        1149
#define IDC_TOOLBAR_ADDALL              1149
#define IDC_PREF_DEF_ANIMSCALETITLE2    1149
#define IDC_PREF_VIEW_ANIMSCALETITLE2   1149
#define IDC_VIDMODE_PREVIEW_RENDER      1150
#define IDC_PREF_DEF_ANIMSCALECUSTOM_LARGE 1150
#define IDC_PREF_VIEW_ANIMSCALECUSTOM_LARGE 1150
#define IDC_TOOLBAR_LIST                1151
#define IDC_PREF_DEF_ANIMCUSTOMSPIN_LARGE 1151
#define IDC_PREF_VIEW_ANIMCUSTOMSPIN_LARGE 1151
#define IDC_PREF_DEF_ANIMPERCSTATIC2    1152
#define IDC_PREF_VIEW_ANIMPERCSTATIC2   1152
#define IDC_PREF_VIEW_CTRLACTIVELABEL   1153
#define IDC_PREF_VIEW_CTRLINACTIVELABEL 1154
#define IDC_PREF_VIEW_CTRLINACTIVE      1155
#define IDC_PREF_VIEW_OVERLAYMODE       1156
#define IDC_TOOLBAR_NAME                1157
#define IDC_PREF_VIEW_OVERLAY           1157
#define IDC_TOOLBAR_STATIC              1158
#define IDC_PREF_VIEW_GAMMAEDIT         1158
#define IDC_TOOLBAR_CATEGORIES          1159
#define IDC_PREF_VIEW_GAMMASPIN         1159
#define IDC_TOOLBAR_STATIC2             1160
#define IDC_PREF_VIEW_PICKWEDIT         1160
#define IDC_TOOLBAR_SORT                1161
#define IDC_PREF_VIEW_PICKWSPIN         1161
#define IDC_PREF_VIEW_PICKPXSTATIC      1162
#define IDC_PREF_VIEW_PICKPXSTATIC2     1163
#define IDC_PREF_VIEW_PICKHEDIT         1164
#define IDC_PREF_VIEW_PICKHSPIN         1165
#define IDC_PREF_VIEW_PICKPXSTATIC3     1166
#define IDC_PREF_VIEW_VIEWSTATIC        1166
#define IDC_PREF_VIEW_FAREDIT           1167
#define IDC_PREF_VIEW_NEAREDIT          1169
#define IDC_PREF_VIEW_NEARSPIN          1170
#define IDC_TOOLBAR_MESSAGE             1174
#define IDC_CONTROL_PAGES               1188
#define IDC_SMOOTH_SCROLL               1189
#define IDC_PREF_DEF_USE_GRP            1190
#define ID_RENDQUEUE_SAVE               1191
#define ID_RENDQUEUE_SHOWNETPREFS       1192
#define ID_RENDQUEUE_NETWORK            1200
#define IDC_RENDQUEUE_SHOWBTN           1203
#define IDC_STRING_EDIT                 1204
#define IDC_TIME_SETSTART               1205
#define IDC_TIME_SETEND                 1206
#define ID_RENDQUEUE_SHOWRENDERLOG      1207
#define IDC_PREF_BINS_STAMP_QUALITY     1208
#define IDC_PREF_BINS_GRP1              1209
#define IDC_PREF_BINS_OPEN              1210
#define IDC_PREF_BINS_GRP3              1211
#define IDC_PREF_BINS_GRP2              1212
#define IDC_PREF_BINS_STAMP_FORMAT      1213
#define ID_RENDQUEUE_VERBOSELOG         1214
#define IDC_PREF_BINS_GRP4              1214
#define IDC_PREF_BINS_CHECKERUNDERLAY   1214
#define IDC_EDIT_PRECISION              1215
#define IDC_PREF_BINS_LOADER_BIN        1215
#define ID_RENDQUEUE_FRAMETIMEOUT       1216
#define IDC_PREF_BINS_SAVER_BIN         1216
#define IDC_SLIDER1                     1219
#define IDC_STATIC1                     1220
#define IDC_PREF_CACHE_ACTIVE           1221
#define IDC_STATIC10                    1221
#define IDC_PREF_CACHE_VIEWED           1222
#define IDC_PREF_ALWAYS_CACHE           1223
#define IDC_PREF_REPONSE_STATIC1        1224
#define IDC_PREF_REPONSE_STATIC2        1225
#define IDC_PREF_CACHE_SLOW             1226
#define IDC_PREF_INTERACTIVE_RESPONSE   1227
#define IDC_PREF_INTERACTIVE_RESPONSE_TEXT 1228
#define IDC_PREF_PARALLELISM_TEXT       1229
#define IDC_PREF_CACHE_VALID            1230
#define IDC_PREF_LAYOUT_MAINWINDEF      1231
#define IDC_PREF_LAYOUT_DOFLOAT         1232
#define IDC_PREF_LAYOUT_MAINGRAB        1233
#define IDC_PREF_LAYOUT_NUMFLOAT        1234
#define IDC_PREF_LAYOUT_CURRMAIN        1235
#define IDC_PREF_LAYOUT_RUNTEXT         1236
#define IDC_PREF_LAYOUT_RUNMODE         1237
#define IDC_AUTOPROXY                   1238
#define IDC_AUTOCONTROLCLOSE            1239
#define IDC_AUTOCONTROLHIDE             1240
#define IDC_PREF_LAYOUT_MAINFRAME       1241
#define IDC_PREF_LAYOUT_CHILDFRAME      1242
#define IDC_PREF_LAYOUT_CHILDGRABALL    1243
#define IDC_PREF_LAYOUT_CHILDWHICH      1244
#define IDC_PREF_LAYOUT_CHILDWHICHTEXT  1245
#define IDC_PREF_LAYOUT_CHILDOVERRIDE   1246
#define IDC_PREF_LAYOUT_CHILDWINDEF     1247
#define IDC_PREF_LAYOUT_CHILDGRAB       1248
#define IDC_PREF_LAYOUT_CHILDRUNTEXT    1249
#define IDC_PREF_LAYOUT_CHILDRUNMODE    1250
#define IDC_PREF_LAYOUT_CHILDOPENONNEW  1251
#define IDC_PREF_AUTOLOAD               1252
#define IDC_ABOUT_BUTURL1               1253
#define IDC_REGISTER_TEXT               1254
#define IDC_REGISTER_KEY                1255
#define IDC_REGISTER_SERIAL             1257
#define IDC_PREF_SELECTIONSYNC          1259
#define IDC_REGISTER_URL                1260
#define IDC_PREF_APP_LOOKGRP            1261
#define IDC_PREF_APP_CATLIST            1262
#define IDC_PREF_APP_FROMLIST           1263
#define IDC_PREF_APP_TOLIST             1264
#define IDC_PREF_APP_REMOVE             1265
#define IDC_PREF_APP_ADD                1266
#define IDC_PREF_APP_CATTITLE           1267
#define IDC_PREF_APP_FROMTITLE          1268
#define IDC_PREF_APP_TOTITLE            1269
#define IDC_PREF_VIDMODE_FPF_TXT        1270
#define IDC_PREF_VIDMODE_FPF_EDT        1271
#define IDC_PREF_VIDMODE_FPF_SPIN       1272
#define IDC_PREF_VIDMODE_FPF_TXT2       1273
#define IDC_EDIT1                       1274
#define IDC_TAPEUTILS_SKIPEDIT          1274
#define IDC_GUIDE_X1                    1274
#define IDC_EDIT_EASEOUT                1274
#define IDC_EDIT_TIME                   1274
#define IDC_STATUS_STATUS               1274
#define IDC_RENDER_STEPEDIT             1274
#define ID_RENDQUEUE_LOGEDIT            1274
#define IDC_PREF_MBFREE_EDIT            1274
#define IDC_PREF_CLUSTER_CLASSEDIT      1274
#define IDC_EDIT                        1274
#define IDC_PATHMAP_NAME                1274
#define IDC_PREF_NETWORK_EMAILADDRESSES 1274
#define IDC_PREF_DEBUG_ADDRSPACE_EDIT   1274
#define IDC_EDIT_TURNS                  1274
#define IDC_PREF_TWEAKS_GRAPHICS_MEMORY 1274
#define IDC_EDIT_VALUE                  1274
#define IDC_PREF_LOADER_CACHE_MAXSIZE_EDIT 1274
#define IDC_RENDER_CLASSEDIT2           1275
#define IDC_PATHMAP_PATH                1275
#define IDC_PREF_NETWORK_EMAILSENDER    1275
#define IDC_EDIT_LENGTH                 1275
#define IDC_TOOLBAR_PATHEDIT            1275
#define IDC_PREF_LOADER_SEPARATOR_EDIT  1275
#define IDC_STATUS_FLOW                 1276
#define IDC_EDIT_PITCH                  1276
#define IDC_PREF_NETWORK_SMTPSERVER     1276
#define IDC_TOOLBAR_ICONEDIT            1276
#define IDC_TAPEUTILS_SKIPSPIN          1277
#define IDC_EDIT_SRADIUS                1277
#define IDC_EDIT_ERADIUS                1278
#define IDC_PREF_AUTONEWFLOW            1279
#define IDC_TAPEUTILS_DISKGROUP         1280
#define IDC_TAPEUTILS_LOG               1281
#define IDC_TAPEUTILS_LOGLIST           1282
#define IDC_TAPEUTILS_TAPELIST          1283
#define IDC_TAPEUTILS_CLIPNAME          1284
#define IDC_TAPEUTILS_BROWSE            1285
#define IDC_TAPEUTILS_STATIC            1286
#define IDC_TAPEUTILS_STATIC2           1287
#define IDC_TAPEUTILS_FORMATLIST        1288
#define IDC_TAPEUTILS_STATIC3           1289
#define IDC_COMBINEDCOLORWHEEL          1290
#define IDC_TAPEUTILS_CLIPINFO          1291
#define IDC_TAPEUTILS_PROGRESS          1293
#define IDC_TAPEUTILS_TAPEINFO          1294
#define IDC_TAPEUTILS_CANCEL            1295
#define IDC_TAPEUTILS_ABORT             1295
#define IDC_TAPEUTILS_TAPEGROUP         1298
#define IDC_PREF_DEBUG_ADDRSPACE_EDIT2  1299
#define IDC_TAPEUTILS_SKIPBACK          1300
#define IDC_TAPEUTILS_SKIPFWD           1301
#define IDC_TAPEUTILS_DISK2TAPE         1303
#define IDC_TAPEUTILS_TAPE2DISK         1304
#define IDC_TAPEUTILS_COPYD2T_LABEL     1305
#define IDC_TAPEUTILS_COPYT2D_LABEL     1306
#define IDC_TAPEUTILS_TAPE              1307
#define IDC_TAPEUTILS_DISK              1308
#define IDC_COLOR_MODE                  1309
#define IDC_TAPEUTILS_LOG_LABEL         1309
#define IDC_COLORLABEL                  1310
#define IDC_NEXT_CONTROL                1311
#define IDC_PREF_BATCH_DEV1_DEVICE      1311
#define IDC_GUIDE_Y1                    1312
#define IDC_CLIPNUMLABEL                1312
#define IDC_GUIDE_X2                    1313
#define IDC_PREF_BATCH_DEV2_DEVICE      1313
#define IDC_GUIDE_Y2                    1314
#define IDC_GUIDE_RATIO                 1315
#define IDC_TAPEUTILS_OPTS_CHK_ORIGNUMS 1316
#define IDC_TAPEUTILS_OPTS_CHK_ORIGNAMES 1317
#define IDC_TAPEUTILS_OPTS_T2D_GROUP    1318
#define IDC_TAPEUTILS_OPTS_CHK_PRESERVEDIRS 1319
#define IDC_TAPEUTILS_OPTS_SLIDE_BLOCKING 1320
#define IDC_TAPEUTILS_OPTS_BLOCKING_SLIDE 1320
#define IDC_TAPEUTILS_OPTS_D2T_GROUP    1321
#define IDC_TAPEUTILS_OPTS_CHK_WRITEFMKS 1322
#define IDC_TAPEUTILS_OPTS_BLOCKING_STAT 1323
#define IDC_TAPEUTILS_OPTS_BLOCKING     1324
#define IDC_PROCESSORSLABEL             1325
#define IDC_TAPEUTILS_OPTS_PADDING_SLIDE 1325
#define IDC_TAPEUTILS_OPTS_PADDING_STAT 1326
#define IDC_PROCESSORS_MODE             1327
#define IDC_TAPEUTILS_OPTS_PADDING      1327
#define IDC_PREF_DEBUG_ASSERT           1328
#define IDC_TAPEUTILS_OPTS_PADDING_STAT2 1329
#define IDC_SLIDER_EASEOUT              1329
#define IDC_STATIC_EOUT                 1330
#define IDC_STATIC_EIN                  1331
#define IDC_SLIDER_EASEIN               1332
#define IDC_EDIT_EASEIN                 1333
#define IDC_PREF_DEBUG_MEMDUMP          1338
#define IDC_PREF_DEBUG_FLUSH            1339
#define IDC_PREF_AVI_QUALITYLABEL       1352
#define IDC_PREF_AVI_KEYLABEL           1353
#define IDC_PREF_AVI_RATELABEL          1354
#define IDC_PREF_AVI_DATALABEL          1354
#define IDC_PREF_AVI_MODELABEL          1355
#define IDC_PREF_AVI_MODECOMBO          1356
#define IDC_PREF_AVI_CONFIGURE          1357
#define IDC_PREF_AVI_ABOUT              1358
#define IDC_EDIT_VAL                    1358
#define IDC_PREF_DEF_VIEWCOMBO          1359
#define IDC_PREF_VIEW_VIEWCOMBO         1359
#define IDC_PREF_DEF_VIEWLABEL          1360
#define IDC_PREF_VIEW_VIEWLABEL         1360
#define IDC_PREF_DEF_AOVERLAY           1361
#define IDC_PREF_VIEW_AOVERLAY          1361
#define IDC_PREF_DEF_SMOOTHRESIZE       1362
#define IDC_PREF_VIEW_SMOOTHRESIZE      1362
#define IDC_PREF_DEF_FOLLOWACTIVE       1363
#define IDC_PREF_VIEW_FOLLOWACTIVE      1363
#define IDC_PREF_DEF_MONITORSAFETY      1364
#define IDC_PREF_VIEW_MONITORSAFETY     1364
#define IDC_PREF_DEF_SAFETITLE          1365
#define IDC_PREF_VIEW_SAFETITLE         1365
#define IDC_PREF_DEF_CENTER             1366
#define IDC_PREF_VIEW_CENTER            1366
#define IDC_PREF_DEF_SHOWCONTROLS       1367
#define IDC_PREF_VIEW_SHOWCONTROLS      1367
#define IDC_PREF_DEF_FILM               1368
#define IDC_PREF_VIEW_FILM              1368
#define IDC_PREF_VIEW_SCALEGRP          1369
#define IDC_PREF_VIEW_OPTIONSGRP        1370
#define IDC_PREF_VIEW_GUIDESGRP         1371
#define IDC_PREF_VIEW_COLORGRP          1372
#define IDC_PREF_VIEW_ONTOP             1373
#define IDC_PREF_VIEW_LUTGRP            1374
#define IDC_PREF_VIEW_CTRLACTIVE        1375
#define IDC_G1STATIC                    1376
#define IDC_PREF_VIEW_PICKGRP           1376
#define IDC_G2STATIC                    1377
#define IDC_PREF_VIEW_LUTLABEL          1378
#define IDC_PREF_VIEW_DEPTHGRP          1378
#define IDC_PREF_VIEW_LUT               1379
#define IDC_PREF_VIEW_LUTBROWSE         1380
#define IDC_PREF_VIEW_GAMMALABEL        1381
#define IDC_PREF_VIEW_GAMMASLIDER       1382
#define IDC_PREF_BATCH_DEV2_GRP         1383
#define IDC_PREF_VIEW_PICKWLABEL        1383
#define IDC_PREF_BATCH_DEV2_CAPS        1384
#define IDC_PREF_VIEW_PICKHLABEL        1384
#define IDC_PREF_BATCH_DEV1_CAPS        1385
#define IDC_PREF_VIEW_FARLABEL          1385
#define IDC_PREF_BATCH_DEV1_CONFIG      1386
#define IDC_PREF_VIEW_NEARLABEL         1386
#define IDC_PREF_BATCH_DEV1_CONFIG2     1387
#define IDC_PREF_BATCH_DEV2_CONFIG      1387
#define ID_VIEW_SHOWCONTROLS            1388
#define IDC_PREFS_PREVIEW_TYPE_AVI      1390
#define IDC_PREFS_PREVIEW_TYPE_FLIPBOOK 1391
#define IDC_PREFS_PREVIEW_DEPTH_16      1392
#define IDC_PREFS_PREVIEW_DEPTH_24      1393
#define IDC_PREFS_PREVIEW_DEPTH_32      1394
#define IDC_PREFS_PREVIEW_DEPTH_MATCH   1395
#define IDC_PREFS_PREVIEW_DEPTH_IMAGE   1396
#define IDC_BCCRASHREC_SRCFILE          1399
#define IDC_BCCRASHREC_SRCBROWSE        1400
#define IDC_BCCRASHREC_DESTBROWSE       1401
#define IDC_BCCRASHREC_SRC              1402
#define IDC_BCCRASHREC_SRC_USEBLACK     1403
#define IDC_BCCRASHREC_SRC_USETESTPATTERN 1404
#define IDC_BCCRASHREC_SRC_USEFILE      1405
#define IDC_BCCRASHREC_DEST             1406
#define IDC_BCCRASHREC_DEST_FILELABEL   1407
#define IDC_BCCRASHREC_DESTFILE         1408
#define IDC_BCCRASHREC_NOTC             1409
#define IDC_BCCRASHREC_TC               1410
#define IDC_BCCRASHREC_DEST_TCSTART     1411
#define IDC_BCCRASHREC_SRC_LOOP         1412
#define IDC_BCCRASHREC_SRC_PREROLL      1413
#define IDC_BCCRASHREC_SRC_TCFILESTART  1413
#define IDC_BCCRASHREC_DEST_PREROLL     1414
#define IDC_BCCRASHREC_SRC_TCFILESTART_LABEL 1416
#define IDC_BCCRASHREC_DEST_CRASHREC    1417
#define IDC_BCCRASHREC_DEST_ASSEMBLE    1418
#define IDC_PREF_NETWORK_TXT            1418
#define IDC_BCCRASHREC_DEST_INSERT      1419
#define IDC_PREF_NETWORK_CUST_GRP       1419
#define IDC_PREF_NETWORK_CBOX           1420
#define IDC_PREF_NETWORK_CUST_GRP2      1420
#define IDC_PREF_NETWORK_NEWBTN         1421
#define IDC_PREF_NETWORK_COPYBTN        1422
#define IDC_PREF_NETWORK_DELBTN         1423
#define IDC_PREF_NETWORK_IP1            1424
#define IDC_PREF_NETWORK_SERVER_IP1     1424
#define IDC_PREF_NETWORK_IP2            1425
#define IDC_PREF_NETWORK_SERVER_IP2     1425
#define IDC_PREF_NETWORK_IP3            1426
#define IDC_PREF_NETWORK_SERVER_IP3     1426
#define IDC_PREF_NETWORK_IP4            1427
#define IDC_PREF_NETWORK_SERVER_IP4     1427
#define IDC_ABOUT_MORE                  1428
#define IDC_PREF_NETWORK_SERVER_NAME    1428
#define IDC_ABOUT_PLUGINLOGO            1429
#define IDC_PREF_NETWORK_SLAVE_IP5      1429
#define IDC_ABOUT_PLUGINURL             1430
#define IDC_PREF_NETWORK_SLAVE_IP6      1430
#define IDC_ABOUT_PLUGINTREE            1431
#define IDC_PREF_NETWORK_SLAVE_IP7      1431
#define IDC_ABOUT_PLUGINTEXT            1432
#define IDC_PREF_NETWORK_SLAVE_IP8      1432
#define IDC_ABOUT_RICHEDIT              1433
#define IDC_PREF_NETWORK_SLAVE_NAME     1433
#define IDC_BCCRASHREC_DEST_TCREGEN     1435
#define IDC_BCCRASHREC_DEST_TCPRESET    1436
#define IDC_BCCRASHREC_DEST_EDITMODELABEL 1438
#define IDC_BCCRASHREC_DEST_TCDROPF     1439
#define IDC_BCCRASHREC_DEST_TCLABEL     1440
#define IDC_PREF_NETWORK_ENABLED        1441
#define IDC_BATCHCLIP_STV_FRAME         1442
#define IDC_BATCHCLIP_DTV_FRAME         1443
#define IDC_PREFS_PREVIEW_FULLSIZE      1444
#define IDC_PREFS_PREVIEW_HALFSIZE      1445
#define IDC_PREFS_PREVIEW_THIRDSIZE     1446
#define IDC_PREFS_PREVIEW_QUARTERSIZE   1447
#define IDC_PREFS_PREVIEW_CUSTOMSIZE    1448
#define IDC_PREF_PREVIEW_WIDTHLABEL     1449
#define IDC_PREF_PREVIEW_HEIGHTLABEL    1450
#define ID_BATCHCLIP_GETTC_SRCIN        1451
#define ID_BATCHCLIP_GETTC_SRCOUT       1452
#define IDC_PREFS_NETWORK_CLIENT        1452
#define IDC_PREF_NETWORK_CLIENT         1452
#define ID_BATCHCLIP_GETTC_DESTIN       1453
#define IDC_PREFS_NETWORK_SERVER        1453
#define IDC_PREF_NETWORK_SERVER         1453
#define ID_BATCHCLIP_GETTC_DESTOUT      1454
#define IDC_PREF_NETWORK_RENDERALL      1454
#define IDC_PREFS_NETWORK_SLAVE_LIST    1455
#define IDC_PREF_NETWORK_SLAVE_LIST     1455
#define IDC_PREF_NETWORK_MAILONJOBDONE  1455
#define IDC_PREF_NETWORK_SERVER_IP      1456
#define IDC_IPADDRESS1                  1457
#define IDC_PREF_NETWORK_SLAVE_IP       1457
#define IDC_PREF_NETWORK_MAILONJOBFAILURE 1457
#define IDC_PREF_NETWORK_MAILONQUEUEDONE 1458
#define IDC_EDIT2                       1459
#define IDC_STATUS_IP                   1459
#define IDC_RENDER_RANGEEDIT            1459
#define IDC_PREF_NETWORK_LOGLINES       1459
#define IDC_EDIT_VAL2                   1459
#define IDC_TOOLBAR_NAMEEDIT            1459
#define IDC_PREF_NETWORK_OVERRIDESENDER 1460
#define IDC_STATUS_PROGRESS             1461
#define IDC_STATIC3                     1462
#define IDC_STATIC4                     1463
#define IDC_STATIC5                     1464
#define IDC_STATIC6                     1465
#define IDC_STATIC7                     1466
#define IDC_STATIC8                     1467
#define IDC_STATIC9                     1468
#define IDC_PREFS_PREVIEW_FULLSIZE_LABEL 1469
#define IDC_PREFS_PREVIEW_HALFSIZE_LABEL 1470
#define IDC_PREFS_PREVIEW_THIRDSIZE_LABEL 1471
#define IDC_PREFS_PREVIEW_QUARTERSIZE_LABEL 1472
#define IDC_PREFS_PREVIEW_CUSTOMSIZE_LABEL 1473
#define IDC_PREFS_PREVIEW_DEPTH_MATCH_LABEL 1474
#define IDC_PREFS_PREVIEW_DEPTH_16_LABEL 1475
#define IDC_PREFS_PREVIEW_DEPTH_24_LABEL 1476
#define IDC_PREFS_PREVIEW_DEPTH_32_LABEL 1477
#define IDC_PREF_VIDEOSPLASH            1478
#define IDC_PREFS_PREVIEW_DEPTH_IMAGE_LABEL 1478
#define IDC_STATUS_NAME                 1479
#define IDC_PREF_VIDEOSPLASH2           1479
#define IDC_CUSTOM1                     1483
#define IDC_BATCHCLIP_SRCEE             1484
#define IDC_BATCHCLIP_DESTEE            1485
#define IDC_SPLINE_TREE                 1486
#define IDC_OP_TREE                     1487
#define IDC_PREF_VIEW_ONE2ONE           1488
#define IDC_PREF_CACHE_SOURCE           1489
#define IDC_PREF_CACHE_LOADER           1490
#define IDC_PREF_CACHE_BRANCH           1491
#define IDC_LIST_HIDDEN                 1492
#define IDC_LIST_ACTIVE                 1493
#define IDC_PREF_VIEW_LIST              1493
#define IDC_BUTTON_RIGHT                1494
#define IDC_PREF_VIEW_LUTPLUGINLIST     1494
#define IDC_BUTTON_LEFT                 1495
#define IDC_STATIC_EXP1                 1496
#define IDC_RANGE_SLIDER                1501
#define IDC_TIME_RANGE_START            1502
#define IDC_TIME_RANGE_END              1503
#define IDC_PREF_DEBUG_CLOSEFILE        1504
#define IDC_PREF_DEBUG_LINEINFO         1505
#define IDC_CHECK_TIME                  1506
#define IDC_LICENSE_MORE                1507
#define IDC_TAB1                        1508
#define IDC_PREF_PREVIEW_OUTDEVICE      1509
#define IDC_CHECK_VALUE                 1510
#define IDC_RADIO_R                     1510
#define IDC_RADIO_G                     1511
#define IDC_RADIO_B                     1512
#define IDC_RADIO_A                     1513
#define IDC_PREF_SMOOTH_ZOOM            1514
#define IDC_PREF_FLOW_FORCE_ALLPIC      1515
#define IDC_PREF_SHOWRENDERSETTINGS     1515
#define IDC_PREF_FLOW_FORCE_SOURCEPIC   1516
#define IDC_PREF_SHOWRENDERSETTINGS2    1516
#define IDC_PREF_CHECKFORUPDATES        1516
#define IDC_PREF_SUMMARIZELOADERRORS    1516
#define IDC_PREF_FLOW_FORCE_ACTIVEPIC   1517
#define IDC_PREF_HOVERWHEEL             1517
#define IDC_PREF_HOVERZOOMWHEEL         1517
#define IDC_PREF_FLOW_FORCE_NAME        1518
#define IDC_PREF_FLOW_FORCE_MODES       1519
#define IDC_PREF_CLIPNUMRADIO_ZERO      1520
#define IDC_PREF_CLIPNUMRADIO_ONE       1521
#define IDC_PREF_CLIPNUMRADIO_SEQ       1522
#define IDC_COLOR_MODE1                 1523
#define IDC_COLOR_MODE8                 1524
#define IDC_COLOR_MODE16                1525
#define IDC_PREF_FLOW_PIPE_ONTOP        1526
#define IDC_PREF_FLOW_PIPE_GRAB         1527
#define IDC_PREF_FLOW_DIRECTION         1528
#define IDC_PREF_FLOW_SHOW_GRID         1529
#define IDC_PREF_FLOW_SCALE             1530
#define IDC_PREF_FLOW_SCALETITLE        1531
#define IDC_PREF_FLOW_SCALECUSTOM       1532
#define IDC_PREF_FLOW_CUSTOMSPIN        1533
#define IDC_PREF_SCRIPT_LOGIN_PASSWORD  1533
#define IDC_PREF_FLOW_PERCSTATIC        1534
#define IDC_PREF_GRP3                   1535
#define IDC_PREF_FLOW_STAT3             1536
#define IDC_PREF_FLOW_STAT4             1537
#define IDC_PREF_FLOW_GRABDIST          1538
#define IDC_PREF_GRP4                   1539
#define IDC_PREF_FLOW_DIRLABEL          1540
#define IDC_PREF_FLOW_GRIDSNAP          1541
#define IDC_PREF_FLOW_PIPESONTOP        1542
#define IDC_PREF_FLOW_AUTOSNAP          1543
#define IDC_PREF_TWEAKS_GRP1            1544
#define IDC_PREF_TWEAKS_GRP2            1545
#define IDC_PREF_TWEAKS_CANCELIO        1546
#define IDC_PREF_TWEAKS_DIRECTREADS     1547
#define IDC_PREF_TWEAKS_TIMEOUTS        1548
#define IDC_PREF_TWEAKS_NUMTIMEOUTS     1548
#define IDC_PREFS_TWEAKS_BEAT_INTERVAL  1549
#define IDC_PREF_TWEAKS_READAHEADBUFS   1550
#define IDC_LIST                        1550
#define IDC_PREF_TWEAKS_GRP3            1551
#define IDC_PREF_TWEAKS_AUTOSAT         1552
#define IDC_PREF_TIMELINE_CBOX          1552
#define IDC_PREF_TWEAKS_SATPROXYSLIDER  1553
#define IDC_PREF_TIMELINE_CUST_GRP      1553
#define IDC_PREFS_TWEAKS_LOADFLOWTIMEOUT 1554
#define IDC_PREF_TIMELINE_NEWBTN        1554
#define IDC_PREF_TIMELINE_COPYBTN       1555
#define IDC_PREFS_TWEAKS_LASTDROPPEDTIMEOUT 1555
#define IDC_PREF_TIMELINE_DELBTN        1556
#define IDC_PREF_TWEAKS_GRP4            1556
#define IDC_PREF_TIMELINE_TREE          1557
#define IDC_PREF_TWEAKS_FLOAT16         1557
#define IDC_PREF_FLOW_ASPECTTILEPICS    1558
#define IDC_PREF_TWEAKS_DIRECTREADS2    1558
#define IDC_PREF_TWEAKS_LUTSHADERS      1558
#define IDC_RENDER_HIQ                  1559
#define IDC_COMBO_FILTER_TO_USE         1559
#define IDC_PREF_FLOW_PIPESTYLE         1560
#define IDC_RENDER_EVERYFRAME           1561
#define IDC_RENDER_RENDERSTEP           1562
#define IDC_RENDER_STEPSPIN             1563
#define IDC_RENDER_NETWORK              1564
#define IDC_PREF_FLOW_PIPESTYLELABEL    1565
#define IDC_PREF_FLOW_SHOWGRID          1566
#define IDC_RENDER_CONFIGLIST           1567
#define IDC_PREF_FLOW_FULLTOOLINDICATOR 1568
#define IDC_RENDER_CONFIGADD            1569
#define IDC_RENDER_CONFIGDELETE         1570
#define IDC_RENDER_WARNINGS             1571
#define IDC_PREF_COMPRESSED_FLOWS       1572
#define IDC_CACHETODISK_BROWSE          1573
#define IDC_CACHETODISK_EDIT            1574
#define IDC_CACHETODISK_RENDERNOW       1575
#define IDC_PREF_TIMELINE_ALL_CAT       1576
#define IDC_CACHETODISK_CLEARCACHE      1576
#define IDC_PREF_TIMELINE_INVERT_CAT    1577
#define IDC_PREF_FLOW_FORCE_MASKPIC     1583
#define IDC_PREF_FLOW_NAVIGATOR_LABEL   1584
#define IDC_PREF_FLOW_SHOW_INSTANCELINKS 1585
#define IDC_PREF_FLOW_SHOW_THUMBNAILS   1586
#define IDC_RENDER_CUSTOMSIZE           1587
#define IDC_RENDER_FULLSIZE             1588
#define IDC_RENDER_HALFSIZE             1589
#define IDC_RENDER_THIRDSIZE            1590
#define IDC_RENDER_QUARTERSIZE          1591
#define IDC_RENDER_KEEP_ASPECT          1592
#define IDC_RENDER_WIDTH                1593
#define IDC_RENDER_HEIGHT               1594
#define IDC_RENDER_FULLSIZE_LABEL       1595
#define IDC_RENDER_HALFSIZE_LABEL       1596
#define IDC_RENDER_THIRDSIZE_LABEL      1597
#define IDC_RENDER_QUARTERSIZE_LABEL    1598
#define IDC_RENDER_CUSTOMSIZE_LABEL     1599
#define IDC_RENDER_WIDTHLABEL           1600
#define IDC_RENDER_HEIGHTLABEL          1601
#define IDC_RENDER_SAVE                 1602
#define IDC_CACHETODISK_USENETWORK      1603
#define IDC_CACHETODISK_ENABLE          1604
#define IDC_CACHETODISK_LOCKBRANCH      1605
#define IDC_CACHETODISK_WARNINGMSG      1606
#define IDC_CACHETODISK_WARNINGMSG2     1607
#define IDC_CACHETODISK_LOCKCACHE       1607
#define IDC_PREF_SCRIPT_LOGIN_REQUIRED  1617
#define IDC_PREF_SCRIPT_LOGIN_NAME_LABEL 1618
#define IDC_PREF_SCRIPT_LOGIN_PASSWORD_LABEL 1619
#define IDC_PREF_SCRIPT_LOGIN_NAME      1620
#define IDC_PREF_FLOW_REMOVE_ROUTERS    1621
#define IDC_PREF_AUTOCLIPBROWSE         1622
#define IDC_PREF_SRIPT_LOGIN_GROUP2     1622
#define IDC_PREF_SRIPT_OPTIONS_GROUP    1622
#define IDC_PREF_VIDMODE_DEPTHLOCK      1623
#define ID_RENDQUEUE_ADDFLOW            1624
#define IDC_PREF_MBFREE_STATIC1         1624
#define IDC_PREF_SCRIPT_LOGIN_NONE3     1624
#define ID_RENDQUEUE_DELFLOW            1625
#define IDC_PREF_MBFREE_STATIC2         1625
#define IDC_RENDQUEUE_FLOWLIST          1626
#define IDC_RENDQUEUE_SLAVELIST         1627
#define IDC_RENDQUEUE_FRAMESLABEL       1628
#define IDC_RENDQUEUE_FRAMESEDIT        1629
#define ID_RENDQUEUE_ADDSLAVE           1630
#define ID_RENDQUEUE_DELSLAVE           1631
#define ID_RENDQUEUE_SCANSLAVES         1632
#define ID_RENDQUEUE_SLAVESETPRIORITYCLASSES 1633
#define ID_RENDQUEUE_FLOWSETPRIORITYCLASS 1634
#define ID_RENDQUEUE_CLEARCOMPLETEDFRAMES 1635
#define ID_RENDQUEUE_LOADSLAVELIST      1636
#define ID_RENDQUEUE_SAVESLAVELIST      1637
#define ID_RENDQUEUE_RETRYSLAVES        1638
#define ID_RENDQUEUE_PAUSEFLOW          1639
#define ID_RENDQUEUE_RESUMEFLOW         1640
#define ID_RENDQUEUE_IMPORTQUEUE        1641
#define ID_RENDQUEUE_STARTUSINGSLAVES   1642
#define ID_RENDQUEUE_STOPUSINGSLAVES    1643
#define ID_RENDQUEUE_FLOWSETTIMEOUT     1644
#define IDC_PREF_GLOBAL_START_STATIC    1645
#define IDC_PREF_GLOBAL_START           1646
#define IDC_PREF_GLOBAL_END_STATIC      1647
#define IDC_PREF_GLOBAL_END             1648
#define IDC_REPORT_BUG_TEXT             1649
#define IDC_COMBO1                      1650
#define IDC_BUG_IMPORTANCE              1650
#define IDC_BUG_TYPE                    1651
#define IDC_PREF_SCRIPT_EDITORLABEL     1657
#define IDC_REPORT_BUG_ATTACHFILE1      1658
#define IDC_REPORT_BUG_ATTACHBROWSE1    1659
#define IDC_SEND_HWCONFIG               1660
#define IDC_SEND_DFCONFIG               1661
#define IDC_PREF_SCRIPT_EDITOR_BROWSE   1661
#define IDC_CC_TO_BETA                  1662
#define IDC_PREF_SCRIPT_EDITOR          1662
#define IDC_REPORT_BUG_SUBJECT          1663
#define IDC_REPORT_BUG_ATTACHFILE2      1664
#define IDC_REPORT_BUG_ATTACHBROWSE2    1665
#define IDC_REPORT_BUG_ATTACHFILE3      1666
#define IDC_REPORT_BUG_ATTACHBROWSE3    1667
#define IDC_REPORT_BUG_ATTACHFILE4      1668
#define IDC_REPORT_BUG_ATTACHBROWSE4    1669
#define IDC_REPORT_BUG_ATTACHFILE5      1670
#define IDC_REPORT_BUG_ATTACHBROWSE5    1671
#define IDC_REPORT_BUG_ATTACHFILE6      1672
#define IDC_REPORT_BUG_ATTACHBROWSE6    1673
#define IDM_BACKGROUND_RENDER           1674
#define IDC_REPORT_BUG_FROM             1674
#define IDC_GROUP                       1675
#define IDC_INDIVIDUAL                  1676
#define IDC_REPORT_BUG_SUBJECT2         1676
#define IDC_REPORT_BUG_SMTPSERVER       1676
#define IDC_PREV                        1677
#define IDC_NEXT                        1678
#define ID_RENDQUEUE_UPDATESOFTWARE     1679
#define ID_RENDQUEUE_VIEWLOG            1680
#define ID_RENDQUEUE_SETMASTER          1681
#define IDC_PREF_CLUSTER_FR_GROUP       1682
#define IDC_PREF_CLUSTER_RENDERRANGE    1683
#define IDC_PREF_CLUSTER_SIDEFRAMES     1684
#define IDC_PREF_CLUSTER_SIDEFRAMES_EDIT 1685
#define IDC_PREF_CLUSTER_CLASS_GROUP    1686
#define IDC_SEND_DRWATSON               1687
#define IDC_PREF_CLUSTER_CLASSLIST      1688
#define IDC_PREF_CLUSTER_RENDER_STATIC  1689
#define IDC_PREF_CLUSTER_FRAMESAROUND_STATIC 1690
#define IDC_RENDER_RANGESTATIC          1691
#define IDC_RENDER_CLASSLIST            1694
#define IDC_RENDER_CLASS_GROUP          1695
#define IDC_RENDER_CLASSLIST_STATIC     1696
#define IDC_RENDER_CLASSSTR_STATIC      1697
#define ID_RENDQUEUE_PAUSE              1698
#define IDC_PREF_SRIPT_LOGIN_GROUP      1698
#define IDC_PREF_SCRIPT_LOGIN_NONE      1699
#define IDC_PREF_SCRIPT_LOGIN_CUSTOM    1700
#define IDC_PREF_SCRIPT_LOGIN_WINDOWS   1701
#define IDC_PREF_VIDMODE_LOADER_LABEL   1702
#define IDC_PREF_VIDMODE_LOADER_FORMAT  1703
#define IDC_PREF_VIDMODE_LOADER_DEFAULT 1704
#define IDC_NETWORK_CLASSLIST           1705
#define IDC_NETWORK_CLASSEDIT           1706
#define IDC_SLIDER                      1707
#define IDC_PATHMAP_LIST                1708
#define IDC_PREF_SOFTDPS_VIDEOOUT_FRAME 1709
#define IDC_PREF_SOFTDPS_VIDEOOUT_LOWPRI 1710
#define IDC_PREF_SOFTDPS_VIDEOOUT_SDTI  1711
#define IDC_PREF_SOFTDPS_SAVE_FRAME     1712
#define IDC_PREF_SOFTDPS_SAVE_UNCOMPRESSED 1713
#define IDC_PREF_SOFTDPS_SAVE_ERRORDIFFUSION 1714
#define IDC_PREF_SOFTDPS_SAVE_DATARATE_LABEL 1715
#define IDC_PREF_SOFTDPS_SAVE_DATARATE  1716
#define IDC_PREF_SOFTDPS_SAVE_DATARATE_LABEL2 1717
#define IDC_PREF_SOFTDPS_SAVE_DOALPHA   1718
#define IDC_PREF_SOFTDPS_SAVE_UNCOMPRESSEDALPHA 1719
#define IDC_PREF_SOFTDPS_SAVE_DATARATEALPHA_LABEL 1720
#define IDC_PREF_SOFTDPS_SAVE_DATARATEALPHA 1721
#define IDC_PREF_SOFTDPS_SAVE_DATARATEALPHA_LABEL2 1722
#define IDC_PREF_SOFTDPS_SCALE_FRAME    1723
#define IDC_PREF_SOFTDPS_SCALE_ENABLE   1724
#define IDC_PREF_SOFTDPS_SCALE_TYPE_LABEL 1725
#define IDC_PREF_SOFTDPS_SCALE_TYPE     1726
#define IDC_PREF_SOFTDPS_SCALE_16_9     1727
#define ID_RENDQUEUE_SLAVE_SCRIPT_EDIT_NEW 1728
#define ID_RENDQUEUE_EDITSLAVES         1729
#define IDC_PATHMAP_NEW                 1730
#define IDC_PATHMAP_DELETE              1731
#define IDC_PREF_SELECTIVEUPDATE_ALL    1732
#define IDC_PREF_SELECTIVEUPDATE_SOME   1733
#define IDC_PREF_SELECTIVEUPDATE_NONE   1734
#define IDC_FIND_MATCHWHOLE             1735
#define IDC_FIND_MATCHCASE              1736
#define IDC_FIND_REGEXP                 1737
#define IDC_FIND_FINDWHAT               1738
#define IDC_FIND_TYPEALL                1739
#define IDC_FIND_TYPENORMAL             1740
#define IDC_FIND_TYPEMASKS              1741
#define IDC_FIND_TYPEMODIFIERS          1742
#define IDC_FIND_TYPEPARTICLES          1743
#define IDC_FIND_TYPESOURCE             1744
#define IDC_PREF_BINS_ADD_LOADER_CLIPS_CHECK 1745
#define IDC_PREF_BINS_ADD_SAVER_CLIPS_CHECK 1746
#define IDC_PREF_NETWORK_CUST_GRP3      1746
#define IDC_PREF_NETWORK_CUST_GRP4      1747
#define IDC_NETWORK_SHOWSLAVES          1749
#define IDC_RENDER_SHOWSLAVES           1750
#define IDC_CHECK_CW                    1750
#define IDC_CHECK_SNAPPOINTS_GUIDES     1750
#define IDC_BINSECURITY_PERMISSION_READ 1750
#define IDC_PREF_VIEW_ENABLELUTS        1750
#define IDC_PREF_SELECT_POINTS_FROM_MULTI_POLIES 1750
#define IDC_CHECK_SELECT_POINTS_FROM_MULTI_POLIES 1750
#define IDC_PREF_TWEAKS_AUTO_DETECT_GRAPHICS_MEMORY 1750
#define IDC_CHECK_EDGE_SHAPE            1750
#define IDC_CHECK_EASEINOUT             1750
#define IDC_PATHMAP_PATHENABLE          1751
#define IDC_BINSECURITY_PERMISSION_CREATE 1751
#define IDC_PREF_VIEW_ENABLESHADERS     1751
#define IDC_PREF_AUTOMATIC_CACHE        1752
#define IDC_BINSECURITY_PERMISSION_MODIFY 1752
#define IDC_CHECK_VALUE2                1753
#define IDC_BINSECURITY_PERMISSION_DELETE 1753
#define IDC_FIND_USE_SEQUENCE           1754
#define IDC_BINSECURITY_PERMISSION_ADMIN 1754
#define IDC_SLIDER_TURNS                1757
#define IDC_RADIO_LENGTH                1758
#define IDC_SLIDER_LENGTH               1759
#define IDC_RADIO_PITCH                 1760
#define IDC_SLIDER_PITCH                1761
#define IDC_STATIC_SRADIUS              1762
#define IDC_SLIDER_SRADIUS              1763
#define IDC_STATIC_ERADIUS              1764
#define IDC_SLIDER_ERADIUS              1765
#define IDC_STATIC_TURNS                1767
#define IDC_SLIDER_WIDTH                1769
#define IDC_SLIDER_HEIGHT               1770
#define IDC_STATIC_HEIGHT               1771
#define IDC_STATIC_WIDTH                1772
#define IDC_EDIT_WIDTH                  1773
#define IDC_EDIT_HEIGHT                 1774
#define IDC_CHECK_SELECTED_TOOLS        1774
#define IDC_CHECK_DISPLAY_POINT_VALUES  1775
#define IDC_CHECK_SHOW_SPREADSHEET      1776
#define IDC_COMBO_TOOLS_MODE            1779
#define IDC_CHECK_CURRENT_TIME          1782
#define IDC_STATIC_OPTIONS              1783
#define IDC_STATIC_TOOLS_MODE           1784
#define IDC_RADIO_SNAPPOINTS_NONE       1787
#define IDC_RADIO_SNAPPOINTS_FIELD      1788
#define IDC_RADIO_SNAPPOINTS_FRAME      1789
#define IDC_RADIO_SNAPGUIDES_NONE       1790
#define IDC_RADIO_SNAPGUIDES_FIELD      1791
#define IDC_RADIO_SNAPGUIDES_FRAME      1792
#define IDC_STATIC_AUTOSNAP_POINTS      1793
#define IDC_STATIC_AUTOSNAP_GUIDES      1794
#define IDC_STATIC_ENABLED              1799
#define IDC_STATIC_SPLINE               1800
#define IDC_STATIC_TIMELINE             1801
#define IDC_RENDER_UPDATEMODE           1802
#define IDC_RENDER_MOTIONBLUR           1803
#define IDC_AUTOCONTROLSELECTED         1804
#define IDC_BINSERVERS_NAME             1805
#define IDC_BINSERVERS_ADD              1806
#define IDC_BINSERVERS_REMOVE           1807
#define IDC_BINSERVERS_LIST             1808
#define IDC_BINSERVERS_USER             1809
#define IDC_PREF_DEF_BSPLINE_QUAD       1809
#define IDC_BINSERVERS_NAME3            1810
#define IDC_BINSERVERS_PASSWORD         1810
#define IDC_PREF_DEF_BSPLINE_CUBIC      1810
#define IDC_BINSERVERS_LIBRARY          1811
#define IDC_PREF_DEF_BSPLINEPLL_CUBIC   1812
#define IDC_BINSERVERS_APPLICATION      1812
#define IDC_PREF_DEF_BSPLINEPLL_QUAD    1813
#define IDC_PREF_BSPLINE_DEGREE_GRP     1814
#define IDC_PREF_BSPLINEPLL_DEGREE_GRP  1815
#define IDC_PREF_VIEW_VIEWSGRP          1818
#define IDC_PREF_VIEW_SETTINGSGRP       1819
#define IDC_PREF_VIEW_RENAME            1820
#define IDC_PREF_VIEW_DELETE            1821
#define IDC_PREF_VIEW_ADDSTATIC         1822
#define IDC_BINSECURITY_LIST            1823
#define IDC_BINSECURITY_ADD             1824
#define IDC_BINSECURITY_REMOVE          1825
#define IDC_BINSECURITY_USER            1826
#define IDC_BINSECURITY_PASSWORD        1827
#define IDC_PREF_SPLINE_SMOOTH_SGRP     1828
#define IDC_BINSECURITY_ROOTPATH        1828
#define IDC_PREF_SPLINES_SCHK           1829
#define IDC_PREF_POLYLINES_SCHK         1830
#define IDC_PREF_BPOLYLINES_SCHK        1831
#define IDC_PREF_BSPLINE_QUAD           1832
#define IDC_PREF_BSPLINE_CUBIC          1833
#define IDC_PREF_BSPLINEPLL_QUAD        1834
#define IDC_PREF_BSPLINEPLL_CUBIC       1835
#define IDC_PREF_LUTS_SCHK              1836
#define IDC_PREF_PATHS_SCHK             1837
#define IDC_PREF_BSPLINE_DEGREE_SGRP    1838
#define IDC_PREF_BSPLINEPLL_DEGREE_SGRP 1839
#define IDC_CHECK_ANIMATED_TOOLS        1840
#define IDC_PREF_MESHES_SCHK            1841
#define IDC_PREF_TWEAKS_IMGOVERLAYSTATIC 1842
#define IDC_PREF_TWEAKS_IMGOVERLAY_NONE 1843
#define IDC_PREF_TWEAKS_IMGOVERLAY_OUTSIDE 1844
#define IDC_PREF_TWEAKS_IMGOVERLAY_ALL  1845
#define IDC_PREF_TWEAKS_USE_10_BIT_FRAMEBUFFER 1846
#define IDC_FORMAT                      1848
#define IDC_RADIO_MOT                   1849
#define IDC_RADIO_SHAPE                 1850
#define IDC_RADIO_POINT_SAMPLES         1851
#define IDC_RADIO_BEZIER_POINTS         1852
#define IDC_RADIO_KEY_POINTS            1853
#define IDC_RADIO_RELATIVE              1854
#define IDC_RADIO_ABSOLUTE              1855
#define IDC_RADIO_LWMOT                 1856
#define IDC_PREF_TRACKER_POINTS_SHOW_SGRP 1857
#define IDC_PREF_TRACKER_POINTS_HIDE    1858
#define IDC_PREF_TRACKER_POINTS_SHOW    1859
#define IDC_PREF_TRACKER_POINTS_SHOW_ON_HOVER 1860
#define IDC_PREF_BSPLINES_SCHK          1861
#define IDC_PATHMAP_BROWSE              1865
#define IDC_PREF_VIDMODE_LOADER_ASPECT_LABEL 1866
#define IDC_PREF_VIDMODE_LOADER_ASPECT_FROMFILE 1867
#define IDC_PREF_VIDMODE_LOADER_ASPECT_DEFAULT 1868
#define IDC_EXPORT_ALUT_RGB             1869
#define IDC_EXPORT_ALUT_RGBA            1870
#define IDC_EXPORT_ALUT_SIXTEEN         1871
#define IDC_EXPORT_ALUT_EIGHT           1872
#define IDC_EXPORT_ALUT_NORMALISED      1873
#define IDC_SLIDER_VALUE                1874
#define IDC_PREF_TWEAKS_TEXTURE_AUTO    1875
#define IDC_PREF_TWEAKS_TEXTURE_INT8    1876
#define IDC_PREF_TWEAKS_TEXTURE_NATIVE  1877
#define IDC_PREF_TWEAKS_TEXTURE_STATIC  1878
#define IDB_GAME_BLOCK                  1879
#define IDC_PREF_TWEAKS_SMR_STATIC      1879
#define IDB_GAME_BLOCK_SHADOW           1880
#define IDC_PREF_TWEAKS_SMR_AUTO        1880
#define IDB_GAME_BALL                   1881
#define IDC_PREF_TWEAKS_SMR_INT         1881
#define IDB_GAME_BALL_SHADOW            1882
#define IDC_PREF_TWEAKS_SMR_FLT16       1882
#define IDB_GAME_PADDLE                 1883
#define IDC_PREF_TWEAKS_TEXTURE_NATIVE3 1883
#define IDC_PREF_TWEAKS_SMR_FLT32       1883
#define IDB_GAME_PADDLE_SHADOW          1884
#define IDB_GAME_PU_DIFFUSE             1885
#define IDB_GAME_PU_SPECULAR            1886
#define IDB_GAME_PU_SHADOW              1887
#define IDB_GAME_PU_CLASSIC             1888
#define IDB_GAME_PADDLE_CLASSIC         1889
#define IDC_REGISTER_MORE               1890
#define IDC_SLIDER_LEFT_SAMPLE_COUNT    1891
#define IDC_SLIDER_SAMPLE_WIDTH         1891
#define IDC_EDIT_LEFT_SAMPLE_COUNT      1892
#define IDC_EDIT_SAMPLE_WIDTH           1892
#define IDC_SLIDER_RIGHT_SAMPLE_COUNT   1893
#define IDC_EDIT_RIGHT_SAMPLE_COUNT     1894
#define IDC_SLIDER_ORDER                1895
#define IDC_EDIT_ORDER                  1896
#define IDC_SLIDER_SAMPLE_SPACING       1897
#define IDC_EDIT_SAMPLE_SPACING         1898
#define IDC_TOOLBAR_NAMESTATIC          1899
#define IDC_TOOLBAR_ICONSTATIC          1900
#define IDC_TOOLBAR_PATHSTATIC          1901
#define IDC_TOOLBAR_PATHBROWSE          1902
#define IDC_PREF_SIMPLECOPIES           1903
#define IDC_PREF_FLOW_NAVIGATOR_OFF     1904
#define IDC_PREF_FLOW_NAVIGATOR_ON      1905
#define IDC_PREF_FLOW_NAVIGATOR_AUTO    1906
#define IDC_STATIC_IN                   1907
#define IDC_STATIC_OUT                  1908
#define IDC_PREF_TRACKER_PATH_SGRP      1909
#define IDC_PREF_TRACKER_PATH_BEZIER    1910
#define IDC_PREF_TRACKER_PATH_BSPLINE   1911
#define IDC_PREF_TRACKER_PATH_XYPATH    1912
#define IDC_STATIC_SPLINE_EDITOR        1917
#define IDC_RADIO_SNAPPOINTS_NONES      1918
#define IDC_RADIO_SNAPPOINTS_FIELDS     1919
#define IDC_RADIO_SNAPPOINTS_FRAMES     1920
#define IDC_CHECK_SNAPPOINTS_GUIDESS    1922
#define IDC_STATIC_AUTOSNAPGUIDES       1923
#define IDC_STATIC_AUTOSNAP_GUIDESS     1923
#define IDC_RADIO_SNAPGUIDES_NONES      1924
#define IDC_RADIO_SNAPGUIDES_FIELDS     1925
#define IDC_RADIO_SNAPGUIDES_FRAMES     1926
#define IDC_STATIC_LUTVIEW              1927
#define IDC_CHECK_AUTOSCALE             1930
#define IDC_CHECK_INDEPENDENT_HANDLES   1931
#define IDC_CHECK_SHOW_KEY_MARKERS      1932
#define IDC_CHECK_FOLLOW_ACTIVE         1933
#define IDC_CHECK_LUT_INDEPENDENT_HANDLES 1934
#define IDC_CHECK_LUT_SHOW_KEY_MARKERS  1935
#define IDC_STATIC_AUTOSNAP_POINTSS     1936
#define IDC_CHECK_TIMELINE_AUTOSCALE    1937
#define IDC_CHECK_SHOW_TIPS             1938
#define IDC_CHECK_LUT_SHOW_TIPS         1939
#define IDC_CHECK1                      1940
#define IDC_CHECK_TIMELINE_SHOW_TIPS    1940
#define IDC_PREF_LOADER_CACHE_ENABLE    1940
#define IDC_CHECK_IMPORT_ALL            1940
#define IDC_EXPORT_3DLUT_EIGHT          1941
#define IDC_EXPORT_3DLUT_SIXTEEN        1942
#define IDC_EXPORT_3DLUT_FLOAT          1943
#define IDC_EXPORT_3DLUT_PRECISION      1944
#define IDC_EXPORT_3DLUT_PATHEDIT       1945
#define IDC_EXPORT_3DLUT_PATHSTATIC     1946
#define IDC_EXPORT_3DLUT_BROWSE         1947
#define IDC_EXPORT_3DLUT_RANGE          1948
#define IDC_EXPORT_3DLUT_RANGE1         1949
#define IDC_EXPORT_3DLUT_RANGE8         1950
#define IDC_EXPORT_3DLUT_RANGE32        1951
#define IDC_STATIC_AUTOSCALES           1951
#define IDC_EXPORT_3DLUT_SIZE17         1952
#define IDC_RADIO_AUTOSCALE_NONES       1952
#define IDC_EXPORT_3DLUT_SIZE33         1953
#define IDC_RADIO_AUTOSCROLLS           1953
#define IDC_EXPORT_3DLUT_SIZE65         1954
#define IDC_RADIO_AUTOFITS              1954
#define IDC_EXPORT_3DLUT_SIZE256        1955
#define IDC_STATIC_AUTOSCALE            1955
#define IDC_EXPORT_3DLUT_CUBESIZE       1956
#define IDC_RADIO_AUTOSCALE_NONE        1956
#define IDC_RADIO_AUTOSCROLL            1957
#define IDC_RADIO_AUTOFIT               1958
#define IDC_STATIC_AUTOSCALE_LUT        1959
#define IDC_RADIO_AUTOSCALE_LUT_NONE    1960
#define IDC_RADIO_AUTOSCROLL_LUT        1961
#define IDC_RADIO_AUTOFIT_LUT           1962
#define IDC_PREF_LOADER_DEFAULTS_GRP    1963
#define IDC_PREF_LOADER_DEPTH_LABEL     1964
#define IDC_PREF_LOADER_DEPTH_FORMAT    1965
#define IDC_PREF_LOADER_DEPTH_DEFAULT   1966
#define IDC_PREF_LOADER_ASPECT_FROMFILE 1967
#define IDC_PREF_LOADER_ASPECT_DEFAULT  1968
#define IDC_PREF_LOADER_ASPECT_LABEL    1969
#define IDC_PREF_LOADER_CACHE_MULTIFRAME 1970
#define IDC_PREF_LOADER_CACHE_MAXSIZE   1971
#define IDC_PREF_LOADER_CACHE_NOLOCAL   1972
#define IDC_PREF_LOADER_LOCATION_EDIT   1973
#define IDC_PREF_LOADER_LOCATION_BROWSE 1974
#define IDC_PREF_LOADER_LOCATION_CLEAR  1975
#define IDC_PREF_LOADER_LOCATION_EXPLORE 1976
#define IDC_PREF_LOADER_MB_LABEL        1977
#define IDC_PREF_LOADER_LOCATION_LABEL  1978
#define IDC_PREF_LOADER                 1979
#define IDC_PREF_LOADER_CACHE_LOCALDISKCACHE 1979
#define IDC_PREF_LOADER_MISSING_LABEL   1980
#define IDC_PREF_LOADER_CACHE_LOCALDISKCACHE2 1981
#define IDC_PREF_LOADER_CACHE_DISABLEALL 1981
#define IDC_PREF_LOADER_MISSING_FAIL    1982
#define IDC_PREF_LOADER_MISSING_LOAD    1983
#define IDC_PREF_POLYLINE_EDIT_MODE_SGRP 1983
#define IDC_PREF_LOADER_MISSING_LOAD2   1984
#define IDC_PREF_LOADER_MISSING_DELETE  1984
#define IDC_PREF_POLYLINE_INSERT_AND_MODIFY 1985
#define IDC_RADIO2                      1986
#define IDC_PREF_POLYLINE_MODIFY_ONLY   1986
#define ID_RENDQUEUE_RETRYFLOW          1987
#define IDC_PREF_LOADER_SEPARATOR_LABEL 1988
#define IDC_PREF_OPENCL_DEBUG_GRP       1989
#define IDC_PREF_OPENCL_VERBOSE         1990
#define IDC_PREF_OPENCL_SHOWPERF        1991
#define IDC_PREF_OPENCL_ENABLE_DISABLE  1992
#define IDC_PREF_OPENCL_ENABLE_ENABLE   1993
#define IDC_PREF_OPENCL_ENABLE_AUTO     1994
#define IDC_PREF_OPENCL_OPTIONS_GRP     1995
#define IDC_PREF_OPENCL_STATUS_GRP      1996
#define IDC_PREF_OPENCL_COMPILEOPTIONS_LABEL 1997
#define IDC_PREF_OPENCL_COMPILEOPTIONS_EDIT 1998
#define IDC_PREF_OPENCL_DEVICE_LABEL    1999
#define IDC_PREF_OPENCL_ENABLE_LABEL    2000
#define IDC_PREF_OPENCL_DEVICE_GPU      2002
#define IDC_PREF_OPENCL_DEVICE_CPU      2003
#define IDC_PREF_OPENCL_DEVICE_NVIDIA   2004
#define IDC_PREF_OPENCL_DEVICE_AMD      2005
#define IDC_PREF_OPENCL_DEVICE_AUTO     2006
#define IDC_PREF_OPENCL_CACHE_CLEAR     2007
#define IDC_PREF_OPENCL_STATUS_LABEL    2008
#define IDC_COMBO_SHAPE_INDEX           2009
#define IDC_COMBO_SHAPEINDEX            2009
#define IDM_OPADD_COMMAND_BASE          10000
#define IDM_OPADD_COMMAND_END           19999
#define ID_VIEWON_BASE                  20000
#define ID_VIEWON_1                     20000
#define ID_VIEWON_2                     20001
#define ID_VIEWON_3                     20002
#define ID_VIEWON_4                     20003
#define ID_VIEWON_5                     20004
#define ID_VIEWON_6                     20005
#define ID_VIEWON_7                     20006
#define ID_VIEWON_8                     20007
#define ID_VIEWON_9                     20008
#define ID_VIEWON_10                    20009
#define ID_VIEWON_END                   20098
#define ID_VIEWON_ALL                   20099
#define ID_TIME_FORWARD                 20100
#define ID_TIME_BACKWARD                20101
#define ID_MODE_UPDATE                  20102
#define ID_MODE_PASSTHROUGH             20103
#define ID_MODE_LOCK                    20104
#define ID_TIME_FORWARD_TO_RENDER       20105
#define ID_TIME_BACKWARD_TO_RENDER      20106
#define ID_TIME_FORWARD_TO_GLOBAL       20107
#define ID_TIME_BACKWARD_TO_GLOBAL      20108
#define IDM_START_FLOW                  32771
#define IDM_TOOLBAROP_DROPPED           32779
#define IDM_OP_DELETE                   32791
#define IDM_OP_VIEW                     32792
#define IDM_STOP_FLOW                   32796
#define ID_OPERATOR_ADD_ADVENTURE_GONORTH_GOSOUTH 32798
#define ID_OPERATOR_ADD_ADVENTURE_GOSOUTH_HORRIBLEMONSTER 32799
#define ID_OPERATOR_ADD_ADVENTURE_GOSOUTH_YOUGETKILLED 32800
#define ID_OPERATOR_ADD_ADVENTURE_GOWEST_POTOFGOLD 32801
#define IDM_OP_CONNECTTO                32806
#define IDM_VIEW_FULLSIZE               32811
#define IDM_VIEW_HALFSIZE               32812
#define IDM_VIEW_QUARTERSIZE            32814
#define IDM_SHOW_TILEPICS               32815
#define IDM_VIEW_EIGHTHSIZE             32816
#define IDM_PREFERENCES                 32820
#define IDM_FILE_PREFERENCES            32822
#define ID_VIEW_OPBAR                   32823
#define IDM_VIEW_THREEQUARTERSIZE       32850
#define IDM_VIEW_CUSTOMISE              32856
#define ID_OPERATOR_ADD_ADVENTURE_GONORTH_LC 32859
#define ID_OPERATOR_ADD_ADVENTURE_CLOBBY 32860
#define ID_OPERATOR_ADD_ADVENTURE_GOWEST_GOSW_PIT 32863
#define ID_OPERATOR_ADD_ADVENTURE_GOWEST_BRANCH 32864
#define ID_OPERATOR_ADD_ADVENTURE_GONORTH_GOSE_GOLD2 32865
#define ID_OPERATOR_ADD_ADVENTURE_GONORTH_GOWEST_GOLD1 32866
#define IDM_VIEW_THIRDSIZE              32867
#define IDM_SHOW_TOOLNAMES              32868
#define ID_VIEW_SHOWFLOWVIEW            32869
#define ID_VIEW_SHOWSPLINEVIEW          32870
#define ID_VIEW_SHOWCONTROLVIEW         32871
#define ID_VIEW_SHOWDISPLAY_LARGE       32873
#define ID_VIEW_SHOWDISPLAY_SMALL       32874
#define ID_VIEW_SHOWBINS                32875
#define ID_PREVIEW_NEW                  32876
#define ID_EDIT_PASTESETTINGS           32877
#define ID_SCALE_TO_FIT                 32878
#define ID_SCALE_100                    32879
#define ID_ZOOM_IN                      32880
#define ID_ZOOM_OUT                     32881
#define ID_VIEW_SHOWMODIFIERVIEW        32882
#define ID_VIEW_COLOR                   32893
#define ID_VIEW_RED                     32894
#define ID_VIEW_GREEN                   32895
#define ID_VIEW_BLUE                    32896
#define ID_VIEW_ALPHA                   32897
#define ID_VIEW_DEPTH                   32898
#define ID_VIEW_SHOWTIMECODES           32899
#define ID_VIEW_VIEWBAR                 32900
#define ID_BATCHVIEW_SHOWTIMECODES      32901
#define IDM_RENDERQUEUE                 32902
#define ID_VIEW_SHOWTIMELINE            32905
#define ID_WEB_SUPPORT                  32906
#define ID_WEB_HELP                     32907
#define ID_WEB_UPDATES                  32908
#define ID_WEB_REGISTRATION             32909
#define ID_WEB_HOME                     32910
#define ID_SCALE_RECTANGLE              32911
#define ID_ABORT                        32912
#define ID_TIMECODE_SMPTE               32913
#define ID_TIMECODE_FEETFRAMES          32914
#define ID_TIME_FORWARD_TO_KEY          32918
#define ID_TIME_BACKWARD_TO_KEY         32919
#define IDM_NETWORKRENDER               32920
#define ID_VIEW_ZEROPADTC               32921
#define ID_BATCHCLIP_SORTSOURCE         32922
#define ID_BATCHCLIP_SORTSRCIN          32923
#define ID_BATCHCLIP_SORTSRCOUT         32924
#define ID_BATCHCLIP_SORTRECORD         32925
#define ID_BATCHCLIP_SORTRECIN          32926
#define ID_BATCHCLIP_SORTRECOUT         32927
#define ID_BATCHCLIP_SORTSTATUS         32928
#define ID_VIEW_MASK                    32929
#define IDM_ALLOWNETWORK                32930
#define IDM_NETWORK_RENDER              32931
#define IDM_STATUS                      32932
#define ID_SWAP_INPUTS                  32933
#define ID_ACCEL32934                   32934
#define ID_ACCEL32935                   32935
#define IDM_PLAY_FLOW                   32936
#define ID_VIEW_SHOWSCRIPTVIEW          32937
#define ID_VIEW_LAYOUT_1                32938
#define ID_VIEW_LAYOUT_2                32939
#define ID_VIEW_LAYOUT_3                32940
#define ID_VIEW_LAYOUT_4                32941
#define ID_VIEW_LAYOUT_5                32942
#define ID_VIEW_LAYOUT_6                32943
#define ID_VIEW_LAYOUT_7                32944
#define ID_VIEW_LAYOUT_8                32945
#define ID_REPORT_BUG                   32946
#define ID_HELP_QUICKREF                32947
#define ID_HELP_UPDATE                  32948
#define ID_PLAY                         32949
#define IDM_MACROEDITOR_OPEN            32950
#define IDM_MACROEDITOR_SAVE            32951
#define IDM_MACROEDITOR_SAVEAS          32952
#define ID_VIEW_LOCKDISPLAY             32953
#define IDM_COLOREDITOR_OPEN            32954
#define IDM_COLOREDITOR_SAVE            32955
#define IDM_COLOREDITOR_SAVEAS          32956
#define IDM_COLOREDITOR_RESET           32957
#define ID_WEB_VFXPEDIA                 32958
#define ID_WEB_VFXPEDIAHELP             32959
#define IDM_UTILITY_COMMAND_BASE        40000
#define IDM_UTILITY_COMMAND_END         40999
#define IDM_TEAR_OFF_START              41000
#define IDM_TEAR_OFF_END                41999
#define IDM_OP_MACRO_BASE               42000
#define IDM_OP_MACRO_END                42999
#define IDM_UTILSCRIPT_EDIT             43000
#define IDM_UTILSCRIPT_COMMAND_BASE     43001
#define IDM_UTILSCRIPT_COMMAND_END      43499
#define IDM_UTILSCRIPT_EDIT_NEW         43500
#define IDM_UTILSCRIPT_EDIT_COMMAND_BASE 43501
#define IDM_UTILSCRIPT_EDIT_COMMAND_END 43999
#define IDM_COMPSCRIPT_EDIT             44000
#define IDM_COMPSCRIPT_COMMAND_BASE     44001
#define IDM_COMPSCRIPT_COMMAND_END      44499
#define IDM_COMPSCRIPT_EDIT_NEW         44500
#define IDM_COMPSCRIPT_EDIT_COMMAND_BASE 44501
#define IDM_COMPSCRIPT_EDIT_COMMAND_END 44999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        770
#define _APS_NEXT_COMMAND_VALUE         32962
#define _APS_NEXT_CONTROL_VALUE         2010
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
